# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from ..errors.payment_required_error import PaymentRequiredError
from ..types.create_simulation_run_response import CreateSimulationRunResponse
from ..types.simulation_run import SimulationRun
from ..types.simulation_run_item import SimulationRunItem
from ..types.simulation_run_payment_required_response import SimulationRunPaymentRequiredResponse
from ..types.simulation_run_transport_configuration import SimulationRunTransportConfiguration
from .types.create_simulation_run_dto_simulations_item import CreateSimulationRunDtoSimulationsItem
from .types.create_simulation_run_dto_target import CreateSimulationRunDtoTarget
from .types.simulation_run_controller_find_all_request_filter_status import (
    SimulationRunControllerFindAllRequestFilterStatus,
)
from .types.simulation_run_controller_find_all_request_sort_by import SimulationRunControllerFindAllRequestSortBy
from .types.simulation_run_controller_find_all_request_sort_order import SimulationRunControllerFindAllRequestSortOrder
from .types.simulation_run_controller_find_all_request_status import SimulationRunControllerFindAllRequestStatus
from .types.simulation_run_controller_find_all_request_target_type import (
    SimulationRunControllerFindAllRequestTargetType,
)
from .types.simulation_run_controller_find_all_response import SimulationRunControllerFindAllResponse
from .types.simulation_run_controller_find_items_request_sort_by import SimulationRunControllerFindItemsRequestSortBy
from .types.simulation_run_controller_find_items_request_sort_order import (
    SimulationRunControllerFindItemsRequestSortOrder,
)
from .types.simulation_run_controller_find_items_request_status import SimulationRunControllerFindItemsRequestStatus
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSimulationRunsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def simulation_run_controller_find_all(
        self,
        *,
        status: typing.Optional[SimulationRunControllerFindAllRequestStatus] = None,
        filter_status: typing.Optional[SimulationRunControllerFindAllRequestFilterStatus] = None,
        target_type: typing.Optional[SimulationRunControllerFindAllRequestTargetType] = None,
        target_id: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[SimulationRunControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[SimulationRunControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SimulationRunControllerFindAllResponse]:
        """
        Returns the simulation runs for the authenticated organization.

        Parameters
        ----------
        status : typing.Optional[SimulationRunControllerFindAllRequestStatus]
            Filter by status

        filter_status : typing.Optional[SimulationRunControllerFindAllRequestFilterStatus]
            Filter by aggregate run result status

        target_type : typing.Optional[SimulationRunControllerFindAllRequestTargetType]
            Filter by target type

        target_id : typing.Optional[str]
            Filter by target id

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[SimulationRunControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[SimulationRunControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SimulationRunControllerFindAllResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            "eval/simulation/run",
            method="GET",
            params={
                "status": status,
                "filterStatus": filter_status,
                "targetType": target_type,
                "targetId": target_id,
                "page": page,
                "sortOrder": sort_order,
                "sortBy": sort_by,
                "limit": limit,
                "createdAtGt": serialize_datetime(created_at_gt) if created_at_gt is not None else None,
                "createdAtLt": serialize_datetime(created_at_lt) if created_at_lt is not None else None,
                "createdAtGe": serialize_datetime(created_at_ge) if created_at_ge is not None else None,
                "createdAtLe": serialize_datetime(created_at_le) if created_at_le is not None else None,
                "updatedAtGt": serialize_datetime(updated_at_gt) if updated_at_gt is not None else None,
                "updatedAtLt": serialize_datetime(updated_at_lt) if updated_at_lt is not None else None,
                "updatedAtGe": serialize_datetime(updated_at_ge) if updated_at_ge is not None else None,
                "updatedAtLe": serialize_datetime(updated_at_le) if updated_at_le is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRunControllerFindAllResponse,
                    construct_type(
                        type_=SimulationRunControllerFindAllResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_run_controller_create(
        self,
        *,
        simulations: typing.Sequence[CreateSimulationRunDtoSimulationsItem],
        target: CreateSimulationRunDtoTarget,
        iterations: typing.Optional[float] = OMIT,
        transport: typing.Optional[SimulationRunTransportConfiguration] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateSimulationRunResponse]:
        """
        Starts a simulation run against a target assistant or squad.

        Parameters
        ----------
        simulations : typing.Sequence[CreateSimulationRunDtoSimulationsItem]
            Array of simulations and/or suites to run

        target : CreateSimulationRunDtoTarget
            Target to test against

        iterations : typing.Optional[float]
            Number of times to run each simulation (default: 1)

        transport : typing.Optional[SimulationRunTransportConfiguration]
            Transport configuration for the simulation runs

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateSimulationRunResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            "eval/simulation/run",
            method="POST",
            json={
                "simulations": convert_and_respect_annotation_metadata(
                    object_=simulations,
                    annotation=typing.Sequence[CreateSimulationRunDtoSimulationsItem],
                    direction="write",
                ),
                "target": convert_and_respect_annotation_metadata(
                    object_=target, annotation=CreateSimulationRunDtoTarget, direction="write"
                ),
                "iterations": iterations,
                "transport": convert_and_respect_annotation_metadata(
                    object_=transport, annotation=SimulationRunTransportConfiguration, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateSimulationRunResponse,
                    construct_type(
                        type_=CreateSimulationRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        SimulationRunPaymentRequiredResponse,
                        construct_type(
                            type_=SimulationRunPaymentRequiredResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_run_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SimulationRun]:
        """
        Returns the specified simulation run, including its status and item counts.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SimulationRun]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRun,
                    construct_type(
                        type_=SimulationRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_run_controller_cancel_group(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SimulationRun]:
        """
        Cancels the specified simulation run.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SimulationRun]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}",
            method="PATCH",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRun,
                    construct_type(
                        type_=SimulationRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_run_controller_find_items(
        self,
        id: str,
        *,
        simulation_id: typing.Optional[str] = None,
        run_id: typing.Optional[str] = None,
        status: typing.Optional[SimulationRunControllerFindItemsRequestStatus] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[SimulationRunControllerFindItemsRequestSortOrder] = None,
        sort_by: typing.Optional[SimulationRunControllerFindItemsRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[SimulationRunItem]]:
        """
        Returns the run items for the specified simulation run.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        simulation_id : typing.Optional[str]
            Filters run items to a specific simulation.

        run_id : typing.Optional[str]
            Filters run items to a specific run.

        status : typing.Optional[SimulationRunControllerFindItemsRequestStatus]
            Filters run items by status.

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[SimulationRunControllerFindItemsRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[SimulationRunControllerFindItemsRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[SimulationRunItem]]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}/item",
            method="GET",
            params={
                "simulationId": simulation_id,
                "runId": run_id,
                "status": status,
                "page": page,
                "sortOrder": sort_order,
                "sortBy": sort_by,
                "limit": limit,
                "createdAtGt": serialize_datetime(created_at_gt) if created_at_gt is not None else None,
                "createdAtLt": serialize_datetime(created_at_lt) if created_at_lt is not None else None,
                "createdAtGe": serialize_datetime(created_at_ge) if created_at_ge is not None else None,
                "createdAtLe": serialize_datetime(created_at_le) if created_at_le is not None else None,
                "updatedAtGt": serialize_datetime(updated_at_gt) if updated_at_gt is not None else None,
                "updatedAtLt": serialize_datetime(updated_at_lt) if updated_at_lt is not None else None,
                "updatedAtGe": serialize_datetime(updated_at_ge) if updated_at_ge is not None else None,
                "updatedAtLe": serialize_datetime(updated_at_le) if updated_at_le is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[SimulationRunItem],
                    construct_type(
                        type_=typing.List[SimulationRunItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_run_controller_find_item(
        self, id: str, item_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SimulationRunItem]:
        """
        Returns the specified run item, including its evaluation results and the ID of the call that ran it.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        item_id : str
            The unique identifier of the run item.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SimulationRunItem]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}/item/{jsonable_encoder(item_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRunItem,
                    construct_type(
                        type_=SimulationRunItem,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_run_controller_cancel_item(
        self, id: str, item_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SimulationRunItem]:
        """
        Cancels the specified run item.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        item_id : str
            The unique identifier of the run item.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SimulationRunItem]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}/item/{jsonable_encoder(item_id)}",
            method="PATCH",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRunItem,
                    construct_type(
                        type_=SimulationRunItem,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_run_controller_generate_suggestions(
        self,
        id: str,
        item_id: str,
        *,
        force: str,
        persist: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        Generates AI suggestions for improving the assistant or squad's system prompt, tools, and scenarios, based on the specified run item.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        item_id : str
            The unique identifier of the run item.

        force : str
            Set to the string `true` to regenerate improvement suggestions even if they already exist.

        persist : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}/item/{jsonable_encoder(item_id)}/generate",
            method="POST",
            params={
                "force": force,
                "persist": persist,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSimulationRunsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def simulation_run_controller_find_all(
        self,
        *,
        status: typing.Optional[SimulationRunControllerFindAllRequestStatus] = None,
        filter_status: typing.Optional[SimulationRunControllerFindAllRequestFilterStatus] = None,
        target_type: typing.Optional[SimulationRunControllerFindAllRequestTargetType] = None,
        target_id: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[SimulationRunControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[SimulationRunControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SimulationRunControllerFindAllResponse]:
        """
        Returns the simulation runs for the authenticated organization.

        Parameters
        ----------
        status : typing.Optional[SimulationRunControllerFindAllRequestStatus]
            Filter by status

        filter_status : typing.Optional[SimulationRunControllerFindAllRequestFilterStatus]
            Filter by aggregate run result status

        target_type : typing.Optional[SimulationRunControllerFindAllRequestTargetType]
            Filter by target type

        target_id : typing.Optional[str]
            Filter by target id

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[SimulationRunControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[SimulationRunControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SimulationRunControllerFindAllResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "eval/simulation/run",
            method="GET",
            params={
                "status": status,
                "filterStatus": filter_status,
                "targetType": target_type,
                "targetId": target_id,
                "page": page,
                "sortOrder": sort_order,
                "sortBy": sort_by,
                "limit": limit,
                "createdAtGt": serialize_datetime(created_at_gt) if created_at_gt is not None else None,
                "createdAtLt": serialize_datetime(created_at_lt) if created_at_lt is not None else None,
                "createdAtGe": serialize_datetime(created_at_ge) if created_at_ge is not None else None,
                "createdAtLe": serialize_datetime(created_at_le) if created_at_le is not None else None,
                "updatedAtGt": serialize_datetime(updated_at_gt) if updated_at_gt is not None else None,
                "updatedAtLt": serialize_datetime(updated_at_lt) if updated_at_lt is not None else None,
                "updatedAtGe": serialize_datetime(updated_at_ge) if updated_at_ge is not None else None,
                "updatedAtLe": serialize_datetime(updated_at_le) if updated_at_le is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRunControllerFindAllResponse,
                    construct_type(
                        type_=SimulationRunControllerFindAllResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_run_controller_create(
        self,
        *,
        simulations: typing.Sequence[CreateSimulationRunDtoSimulationsItem],
        target: CreateSimulationRunDtoTarget,
        iterations: typing.Optional[float] = OMIT,
        transport: typing.Optional[SimulationRunTransportConfiguration] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateSimulationRunResponse]:
        """
        Starts a simulation run against a target assistant or squad.

        Parameters
        ----------
        simulations : typing.Sequence[CreateSimulationRunDtoSimulationsItem]
            Array of simulations and/or suites to run

        target : CreateSimulationRunDtoTarget
            Target to test against

        iterations : typing.Optional[float]
            Number of times to run each simulation (default: 1)

        transport : typing.Optional[SimulationRunTransportConfiguration]
            Transport configuration for the simulation runs

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateSimulationRunResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "eval/simulation/run",
            method="POST",
            json={
                "simulations": convert_and_respect_annotation_metadata(
                    object_=simulations,
                    annotation=typing.Sequence[CreateSimulationRunDtoSimulationsItem],
                    direction="write",
                ),
                "target": convert_and_respect_annotation_metadata(
                    object_=target, annotation=CreateSimulationRunDtoTarget, direction="write"
                ),
                "iterations": iterations,
                "transport": convert_and_respect_annotation_metadata(
                    object_=transport, annotation=SimulationRunTransportConfiguration, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateSimulationRunResponse,
                    construct_type(
                        type_=CreateSimulationRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        SimulationRunPaymentRequiredResponse,
                        construct_type(
                            type_=SimulationRunPaymentRequiredResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_run_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SimulationRun]:
        """
        Returns the specified simulation run, including its status and item counts.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SimulationRun]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRun,
                    construct_type(
                        type_=SimulationRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_run_controller_cancel_group(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SimulationRun]:
        """
        Cancels the specified simulation run.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SimulationRun]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}",
            method="PATCH",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRun,
                    construct_type(
                        type_=SimulationRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_run_controller_find_items(
        self,
        id: str,
        *,
        simulation_id: typing.Optional[str] = None,
        run_id: typing.Optional[str] = None,
        status: typing.Optional[SimulationRunControllerFindItemsRequestStatus] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[SimulationRunControllerFindItemsRequestSortOrder] = None,
        sort_by: typing.Optional[SimulationRunControllerFindItemsRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[SimulationRunItem]]:
        """
        Returns the run items for the specified simulation run.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        simulation_id : typing.Optional[str]
            Filters run items to a specific simulation.

        run_id : typing.Optional[str]
            Filters run items to a specific run.

        status : typing.Optional[SimulationRunControllerFindItemsRequestStatus]
            Filters run items by status.

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[SimulationRunControllerFindItemsRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[SimulationRunControllerFindItemsRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[SimulationRunItem]]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}/item",
            method="GET",
            params={
                "simulationId": simulation_id,
                "runId": run_id,
                "status": status,
                "page": page,
                "sortOrder": sort_order,
                "sortBy": sort_by,
                "limit": limit,
                "createdAtGt": serialize_datetime(created_at_gt) if created_at_gt is not None else None,
                "createdAtLt": serialize_datetime(created_at_lt) if created_at_lt is not None else None,
                "createdAtGe": serialize_datetime(created_at_ge) if created_at_ge is not None else None,
                "createdAtLe": serialize_datetime(created_at_le) if created_at_le is not None else None,
                "updatedAtGt": serialize_datetime(updated_at_gt) if updated_at_gt is not None else None,
                "updatedAtLt": serialize_datetime(updated_at_lt) if updated_at_lt is not None else None,
                "updatedAtGe": serialize_datetime(updated_at_ge) if updated_at_ge is not None else None,
                "updatedAtLe": serialize_datetime(updated_at_le) if updated_at_le is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[SimulationRunItem],
                    construct_type(
                        type_=typing.List[SimulationRunItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_run_controller_find_item(
        self, id: str, item_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SimulationRunItem]:
        """
        Returns the specified run item, including its evaluation results and the ID of the call that ran it.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        item_id : str
            The unique identifier of the run item.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SimulationRunItem]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}/item/{jsonable_encoder(item_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRunItem,
                    construct_type(
                        type_=SimulationRunItem,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_run_controller_cancel_item(
        self, id: str, item_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SimulationRunItem]:
        """
        Cancels the specified run item.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        item_id : str
            The unique identifier of the run item.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SimulationRunItem]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}/item/{jsonable_encoder(item_id)}",
            method="PATCH",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationRunItem,
                    construct_type(
                        type_=SimulationRunItem,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_run_controller_generate_suggestions(
        self,
        id: str,
        item_id: str,
        *,
        force: str,
        persist: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        Generates AI suggestions for improving the assistant or squad's system prompt, tools, and scenarios, based on the specified run item.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation run.

        item_id : str
            The unique identifier of the run item.

        force : str
            Set to the string `true` to regenerate improvement suggestions even if they already exist.

        persist : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/run/{jsonable_encoder(id)}/item/{jsonable_encoder(item_id)}/generate",
            method="POST",
            params={
                "force": force,
                "persist": persist,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
