# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.insight_paginated_response import InsightPaginatedResponse
from ..types.insight_run_format_plan import InsightRunFormatPlan
from ..types.insight_run_response import InsightRunResponse
from ..types.insight_time_range_with_step import InsightTimeRangeWithStep
from .raw_client import AsyncRawInsightClient, RawInsightClient
from .types.insight_controller_create_request import InsightControllerCreateRequest
from .types.insight_controller_create_response import InsightControllerCreateResponse
from .types.insight_controller_find_all_request_sort_by import InsightControllerFindAllRequestSortBy
from .types.insight_controller_find_all_request_sort_order import InsightControllerFindAllRequestSortOrder
from .types.insight_controller_find_one_response import InsightControllerFindOneResponse
from .types.insight_controller_preview_request import InsightControllerPreviewRequest
from .types.insight_controller_remove_response import InsightControllerRemoveResponse
from .types.insight_controller_update_request_body import InsightControllerUpdateRequestBody
from .types.insight_controller_update_response import InsightControllerUpdateResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class InsightClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInsightClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInsightClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInsightClient
        """
        return self._raw_client

    def insight_controller_find_all(
        self,
        *,
        id: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[InsightControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[InsightControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InsightPaginatedResponse:
        """
        Returns saved reporting insights for the authenticated organization. Filter results by ID or creation and update timestamps.

        Parameters
        ----------
        id : typing.Optional[str]
            Filters reporting insights by ID.

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[InsightControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[InsightControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightPaginatedResponse


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.insight.insight_controller_find_all()
        """
        _response = self._raw_client.insight_controller_find_all(
            id=id,
            page=page,
            sort_order=sort_order,
            sort_by=sort_by,
            limit=limit,
            created_at_gt=created_at_gt,
            created_at_lt=created_at_lt,
            created_at_ge=created_at_ge,
            created_at_le=created_at_le,
            updated_at_gt=updated_at_gt,
            updated_at_lt=updated_at_lt,
            updated_at_ge=updated_at_ge,
            updated_at_le=updated_at_le,
            request_options=request_options,
        )
        return _response.data

    def insight_controller_create(
        self, *, request: InsightControllerCreateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> InsightControllerCreateResponse:
        """
        Creates a saved reporting insight that queries call data and presents the results as a bar chart, pie chart, line chart, or text value.

        Parameters
        ----------
        request : InsightControllerCreateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightControllerCreateResponse


        Examples
        --------
        from vapi import JsonQueryOnCallTableWithStringTypeColumn, Vapi
        from vapi.insight import InsightControllerCreateRequest_Bar

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.insight.insight_controller_create(
            request=InsightControllerCreateRequest_Bar(
                queries=[
                    JsonQueryOnCallTableWithStringTypeColumn(
                        type="vapiql-json",
                        table="call",
                        column="id",
                        operation="count",
                    )
                ],
            ),
        )
        """
        _response = self._raw_client.insight_controller_create(request=request, request_options=request_options)
        return _response.data

    def insight_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InsightControllerFindOneResponse:
        """
        Returns the reporting insight identified by its ID.

        Parameters
        ----------
        id : str
            The unique identifier of the reporting insight.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightControllerFindOneResponse


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.insight.insight_controller_find_one(
            id="id",
        )
        """
        _response = self._raw_client.insight_controller_find_one(id, request_options=request_options)
        return _response.data

    def insight_controller_remove(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InsightControllerRemoveResponse:
        """
        Deletes the reporting insight identified by its ID.

        Parameters
        ----------
        id : str
            The unique identifier of the reporting insight.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightControllerRemoveResponse


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.insight.insight_controller_remove(
            id="id",
        )
        """
        _response = self._raw_client.insight_controller_remove(id, request_options=request_options)
        return _response.data

    def insight_controller_update(
        self,
        id: str,
        *,
        request: InsightControllerUpdateRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InsightControllerUpdateResponse:
        """
        Updates the reporting insight identified by its ID.

        Parameters
        ----------
        id : str
            The unique identifier of the reporting insight.

        request : InsightControllerUpdateRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightControllerUpdateResponse


        Examples
        --------
        from vapi import Vapi
        from vapi.insight import InsightControllerUpdateRequestBody_Bar

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.insight.insight_controller_update(
            id="id",
            request=InsightControllerUpdateRequestBody_Bar(),
        )
        """
        _response = self._raw_client.insight_controller_update(id, request=request, request_options=request_options)
        return _response.data

    def insight_controller_run(
        self,
        id: str,
        *,
        format_plan: typing.Optional[InsightRunFormatPlan] = OMIT,
        time_range_override: typing.Optional[InsightTimeRangeWithStep] = OMIT,
        assistant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InsightRunResponse:
        """
        Runs a saved reporting insight, optionally overriding its time range and response format.

        Parameters
        ----------
        id : str
            The unique identifier of the reporting insight.

        format_plan : typing.Optional[InsightRunFormatPlan]
            Output-formatting instructions applied to the insight run.

        time_range_override : typing.Optional[InsightTimeRangeWithStep]
            This is the optional time range override for the insight.
            If provided, overrides every field in the insight's timeRange.
            If this is provided with missing fields, defaults will be used, not the insight's timeRange.
            start default - "-7d"
            end default - "now"
            step default - "day"
            For Pie and Text Insights, step will be ignored even if provided.

        assistant_id : typing.Optional[str]
            Optional runtime assistant scope for dashboards.
            This is applied to call-table queries without mutating the saved insight.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightRunResponse


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.insight.insight_controller_run(
            id="id",
        )
        """
        _response = self._raw_client.insight_controller_run(
            id,
            format_plan=format_plan,
            time_range_override=time_range_override,
            assistant_id=assistant_id,
            request_options=request_options,
        )
        return _response.data

    def insight_controller_preview(
        self, *, request: InsightControllerPreviewRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> InsightRunResponse:
        """
        Runs an insight definition without first saving it, returning a preview of the resulting chart or text value.

        Parameters
        ----------
        request : InsightControllerPreviewRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightRunResponse


        Examples
        --------
        from vapi import JsonQueryOnCallTableWithStringTypeColumn, Vapi
        from vapi.insight import InsightControllerPreviewRequest_Bar

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.insight.insight_controller_preview(
            request=InsightControllerPreviewRequest_Bar(
                queries=[
                    JsonQueryOnCallTableWithStringTypeColumn(
                        type="vapiql-json",
                        table="call",
                        column="id",
                        operation="count",
                    )
                ],
            ),
        )
        """
        _response = self._raw_client.insight_controller_preview(request=request, request_options=request_options)
        return _response.data


class AsyncInsightClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInsightClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInsightClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInsightClient
        """
        return self._raw_client

    async def insight_controller_find_all(
        self,
        *,
        id: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[InsightControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[InsightControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InsightPaginatedResponse:
        """
        Returns saved reporting insights for the authenticated organization. Filter results by ID or creation and update timestamps.

        Parameters
        ----------
        id : typing.Optional[str]
            Filters reporting insights by ID.

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[InsightControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[InsightControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightPaginatedResponse


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.insight.insight_controller_find_all()


        asyncio.run(main())
        """
        _response = await self._raw_client.insight_controller_find_all(
            id=id,
            page=page,
            sort_order=sort_order,
            sort_by=sort_by,
            limit=limit,
            created_at_gt=created_at_gt,
            created_at_lt=created_at_lt,
            created_at_ge=created_at_ge,
            created_at_le=created_at_le,
            updated_at_gt=updated_at_gt,
            updated_at_lt=updated_at_lt,
            updated_at_ge=updated_at_ge,
            updated_at_le=updated_at_le,
            request_options=request_options,
        )
        return _response.data

    async def insight_controller_create(
        self, *, request: InsightControllerCreateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> InsightControllerCreateResponse:
        """
        Creates a saved reporting insight that queries call data and presents the results as a bar chart, pie chart, line chart, or text value.

        Parameters
        ----------
        request : InsightControllerCreateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightControllerCreateResponse


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi, JsonQueryOnCallTableWithStringTypeColumn
        from vapi.insight import InsightControllerCreateRequest_Bar

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.insight.insight_controller_create(
                request=InsightControllerCreateRequest_Bar(
                    queries=[
                        JsonQueryOnCallTableWithStringTypeColumn(
                            type="vapiql-json",
                            table="call",
                            column="id",
                            operation="count",
                        )
                    ],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.insight_controller_create(request=request, request_options=request_options)
        return _response.data

    async def insight_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InsightControllerFindOneResponse:
        """
        Returns the reporting insight identified by its ID.

        Parameters
        ----------
        id : str
            The unique identifier of the reporting insight.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightControllerFindOneResponse


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.insight.insight_controller_find_one(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.insight_controller_find_one(id, request_options=request_options)
        return _response.data

    async def insight_controller_remove(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InsightControllerRemoveResponse:
        """
        Deletes the reporting insight identified by its ID.

        Parameters
        ----------
        id : str
            The unique identifier of the reporting insight.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightControllerRemoveResponse


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.insight.insight_controller_remove(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.insight_controller_remove(id, request_options=request_options)
        return _response.data

    async def insight_controller_update(
        self,
        id: str,
        *,
        request: InsightControllerUpdateRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InsightControllerUpdateResponse:
        """
        Updates the reporting insight identified by its ID.

        Parameters
        ----------
        id : str
            The unique identifier of the reporting insight.

        request : InsightControllerUpdateRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightControllerUpdateResponse


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi
        from vapi.insight import InsightControllerUpdateRequestBody_Bar

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.insight.insight_controller_update(
                id="id",
                request=InsightControllerUpdateRequestBody_Bar(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.insight_controller_update(
            id, request=request, request_options=request_options
        )
        return _response.data

    async def insight_controller_run(
        self,
        id: str,
        *,
        format_plan: typing.Optional[InsightRunFormatPlan] = OMIT,
        time_range_override: typing.Optional[InsightTimeRangeWithStep] = OMIT,
        assistant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InsightRunResponse:
        """
        Runs a saved reporting insight, optionally overriding its time range and response format.

        Parameters
        ----------
        id : str
            The unique identifier of the reporting insight.

        format_plan : typing.Optional[InsightRunFormatPlan]
            Output-formatting instructions applied to the insight run.

        time_range_override : typing.Optional[InsightTimeRangeWithStep]
            This is the optional time range override for the insight.
            If provided, overrides every field in the insight's timeRange.
            If this is provided with missing fields, defaults will be used, not the insight's timeRange.
            start default - "-7d"
            end default - "now"
            step default - "day"
            For Pie and Text Insights, step will be ignored even if provided.

        assistant_id : typing.Optional[str]
            Optional runtime assistant scope for dashboards.
            This is applied to call-table queries without mutating the saved insight.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightRunResponse


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.insight.insight_controller_run(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.insight_controller_run(
            id,
            format_plan=format_plan,
            time_range_override=time_range_override,
            assistant_id=assistant_id,
            request_options=request_options,
        )
        return _response.data

    async def insight_controller_preview(
        self, *, request: InsightControllerPreviewRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> InsightRunResponse:
        """
        Runs an insight definition without first saving it, returning a preview of the resulting chart or text value.

        Parameters
        ----------
        request : InsightControllerPreviewRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InsightRunResponse


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi, JsonQueryOnCallTableWithStringTypeColumn
        from vapi.insight import InsightControllerPreviewRequest_Bar

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.insight.insight_controller_preview(
                request=InsightControllerPreviewRequest_Bar(
                    queries=[
                        JsonQueryOnCallTableWithStringTypeColumn(
                            type="vapiql-json",
                            table="call",
                            column="id",
                            operation="count",
                        )
                    ],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.insight_controller_preview(request=request, request_options=request_options)
        return _response.data
