# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .analysis_cost_analysis_type import AnalysisCostAnalysisType
from .structured_output_cost_breakdown import StructuredOutputCostBreakdown


class AnalysisCost(UncheckedBaseModel):
    """
    Cost for an individual analysis request, including analysis type, model, token usage, and amount.
    """

    analysis_type: typing_extensions.Annotated[
        AnalysisCostAnalysisType,
        FieldMetadata(alias="analysisType"),
        pydantic.Field(alias="analysisType", description="This is the type of analysis performed."),
    ]
    model: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    This is the model that was used to perform the analysis.
    """

    prompt_tokens: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="promptTokens"),
        pydantic.Field(alias="promptTokens", description="This is the number of prompt tokens used in the analysis."),
    ]
    completion_tokens: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="completionTokens"),
        pydantic.Field(
            alias="completionTokens", description="This is the number of completion tokens generated in the analysis."
        ),
    ]
    cached_prompt_tokens: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="cachedPromptTokens"),
        pydantic.Field(
            alias="cachedPromptTokens",
            description="This is the number of cached prompt tokens used in the analysis. This is only applicable to certain providers (e.g., OpenAI, Azure OpenAI) that support prompt caching. Cached tokens are billed at a discounted rate.",
        ),
    ] = None
    structured_output_breakdown: typing_extensions.Annotated[
        typing.Optional[typing.List[StructuredOutputCostBreakdown]],
        FieldMetadata(alias="structuredOutputBreakdown"),
        pydantic.Field(
            alias="structuredOutputBreakdown",
            description="This is the per-structured-output breakdown of this cost. The `cost`, `promptTokens`, `completionTokens` and `cachedPromptTokens` above are the sums of these rows.\n\nThis is only set when `analysisType` is `structuredOutput`, and it is omitted entirely rather than partially populated, so when it is present the rows always reconcile to the totals above.\n\nA structured output that was skipped, or that extracts via regex, makes no LLM call and so has no row here — this is not a complete list of the call's configured structured outputs. There is one row per evaluation, so a `structuredOutputId` can appear more than once if it was evaluated more than once; sum the rows rather than indexing them by id.",
        ),
    ] = None
    cost: float = pydantic.Field()
    """
    This is the cost of the component in USD.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
