# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .artifact_messages_item import ArtifactMessagesItem
from .assistant_activation import AssistantActivation
from .node_artifact import NodeArtifact
from .open_ai_message import OpenAiMessage
from .performance_metrics import PerformanceMetrics
from .recording import Recording
from .skipped_structured_output import SkippedStructuredOutput
from .transfer_artifact import TransferArtifact


class Artifact(UncheckedBaseModel):
    """
    Artifacts generated during a call, including messages, recordings, transcript, logs, packet capture, workflow-node data, variables, performance metrics, structured outputs, scorecards, and transfers.
    """

    messages: typing.Optional[typing.List[ArtifactMessagesItem]] = pydantic.Field(default=None)
    """
    These are the messages that were spoken during the call.
    """

    messages_open_ai_formatted: typing_extensions.Annotated[
        typing.Optional[typing.List[OpenAiMessage]],
        FieldMetadata(alias="messagesOpenAIFormatted"),
        pydantic.Field(
            alias="messagesOpenAIFormatted",
            description="These are the messages that were spoken during the call, formatted for OpenAI.",
        ),
    ] = None
    skipped_structured_outputs: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, SkippedStructuredOutput]],
        FieldMetadata(alias="skippedStructuredOutputs"),
        pydantic.Field(
            alias="skippedStructuredOutputs",
            description="Structured outputs skipped because their conditions were not met, keyed by saved or runtime output ID.",
        ),
    ] = None
    transfers: typing.Optional[typing.List[TransferArtifact]] = pydantic.Field(default=None)
    """
    These are the transfer records for the call's transfer attempts (warm and blind), including
    destination, mode, and status. Warm transfer records also include transcripts and messages.
    """

    recording_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="recordingUrl"),
        pydantic.Field(
            alias="recordingUrl",
            description="This is the recording url for the call. To enable, set `assistant.artifactPlan.recordingEnabled`.",
        ),
    ] = None
    stereo_recording_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="stereoRecordingUrl"),
        pydantic.Field(
            alias="stereoRecordingUrl",
            description="This is the stereo recording url for the call. To enable, set `assistant.artifactPlan.recordingEnabled`.",
        ),
    ] = None
    video_recording_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="videoRecordingUrl"),
        pydantic.Field(
            alias="videoRecordingUrl",
            description="This is video recording url for the call. To enable, set `assistant.artifactPlan.videoRecordingEnabled`.",
        ),
    ] = None
    video_recording_start_delay_seconds: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="videoRecordingStartDelaySeconds"),
        pydantic.Field(
            alias="videoRecordingStartDelaySeconds",
            description="This is video recording start delay in ms. To enable, set `assistant.artifactPlan.videoRecordingEnabled`. This can be used to align the playback of the recording with artifact.messages timestamps.",
        ),
    ] = None
    recording: typing.Optional[Recording] = pydantic.Field(default=None)
    """
    This is the recording url for the call. To enable, set `assistant.artifactPlan.recordingEnabled`.
    """

    transcript: typing.Optional[str] = pydantic.Field(default=None)
    """
    This is the transcript of the call. This is derived from `artifact.messages` but provided for convenience.
    """

    pcap_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="pcapUrl"),
        pydantic.Field(
            alias="pcapUrl",
            description="This is the packet capture url for the call. This is only available for `phone` type calls where phone number's provider is `vapi` or `byo-phone-number`.",
        ),
    ] = None
    log_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="logUrl"),
        pydantic.Field(
            alias="logUrl",
            description="This is the url for the call logs. This includes all logging output during the call for debugging purposes.",
        ),
    ] = None
    nodes: typing.Optional[typing.List[NodeArtifact]] = pydantic.Field(default=None)
    """
    This is the history of workflow nodes that were executed during the call.
    """

    assistant_activations: typing_extensions.Annotated[
        typing.Optional[typing.List[AssistantActivation]],
        FieldMetadata(alias="assistantActivations"),
        pydantic.Field(
            alias="assistantActivations",
            description="Ordered list of assistants that were active during the call, including after transfers and handoffs.",
        ),
    ] = None
    variable_values: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="variableValues"),
        pydantic.Field(
            alias="variableValues", description="These are the variable values at the end of the workflow execution."
        ),
    ] = None
    performance_metrics: typing_extensions.Annotated[
        typing.Optional[PerformanceMetrics],
        FieldMetadata(alias="performanceMetrics"),
        pydantic.Field(
            alias="performanceMetrics",
            description="This is the performance metrics for the call. It contains the turn latency, broken down by component.",
        ),
    ] = None
    structured_outputs: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="structuredOutputs"),
        pydantic.Field(
            alias="structuredOutputs",
            description="These are the structured outputs that will be extracted from the call.\nTo enable, set `assistant.artifactPlan.structuredOutputIds` with the IDs of the structured outputs you want to extract.",
        ),
    ] = None
    scorecards: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    These are the scorecards that have been evaluated based on the structured outputs extracted during the call.
    To enable, set `assistant.artifactPlan.scorecardIds` or `assistant.artifactPlan.scorecards` with the IDs or objects of the scorecards you want to evaluate.
    """

    structured_outputs_last_updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="structuredOutputsLastUpdatedAt"),
        pydantic.Field(
            alias="structuredOutputsLastUpdatedAt", description="This is when the structured outputs were last updated"
        ),
    ] = None
    presigned_mono_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="presignedMonoUrl"),
        pydantic.Field(
            alias="presignedMonoUrl",
            description="This is a presigned URL to download the mono recording without\nauthentication. Populated on API responses and server messages; never\nstored. Expires at `presignedUrlsExpiresAt` — after that, use\n`GET /call/{id}/mono-recording`.",
        ),
    ] = None
    presigned_stereo_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="presignedStereoUrl"),
        pydantic.Field(
            alias="presignedStereoUrl",
            description="This is a presigned URL to download the stereo recording without\nauthentication. Expires at `presignedUrlsExpiresAt` — after that, use\n`GET /call/{id}/stereo-recording`.",
        ),
    ] = None
    presigned_video_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="presignedVideoUrl"),
        pydantic.Field(
            alias="presignedVideoUrl",
            description="This is a presigned URL to download the video recording without\nauthentication. Expires at `presignedUrlsExpiresAt` — after that, use\n`GET /call/{id}/video-recording`.",
        ),
    ] = None
    presigned_assistant_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="presignedAssistantUrl"),
        pydantic.Field(
            alias="presignedAssistantUrl",
            description="This is a presigned URL to download the assistant-channel mono recording\nwithout authentication. Expires at `presignedUrlsExpiresAt`.",
        ),
    ] = None
    presigned_customer_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="presignedCustomerUrl"),
        pydantic.Field(
            alias="presignedCustomerUrl",
            description="This is a presigned URL to download the customer-channel mono recording\nwithout authentication. Expires at `presignedUrlsExpiresAt`.",
        ),
    ] = None
    presigned_pcap_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="presignedPcapUrl"),
        pydantic.Field(
            alias="presignedPcapUrl",
            description="This is a presigned URL to download the packet capture without\nauthentication. Expires at `presignedUrlsExpiresAt`.",
        ),
    ] = None
    presigned_log_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="presignedLogUrl"),
        pydantic.Field(
            alias="presignedLogUrl",
            description="This is a presigned URL to download the call logs without\nauthentication. Expires at `presignedUrlsExpiresAt`.",
        ),
    ] = None
    presigned_urls_expires_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="presignedUrlsExpiresAt"),
        pydantic.Field(
            alias="presignedUrlsExpiresAt",
            description="This is when the presigned URLs above expire, as an ISO 8601 timestamp.\nThe raw `*Url` fields remain the stable identifiers and do not expire.\nPresigned URLs are regenerated per response and per webhook delivery, so\nvalues differ across retries.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
