# This file was auto-generated by Fern from our API Definition.

import typing

AssistantDraftServerMessagesItem = typing.Union[
    typing.Literal[
        "assistant.started",
        "assistant.speechStarted",
        "conversation-update",
        "end-of-call-report",
        "function-call",
        "hang",
        "language-changed",
        "language-change-detected",
        "model-output",
        "phone-call-control",
        "speech-update",
        "status-update",
        "transcript",
        'transcript[transcriptType="final"]',
        "tool-calls",
        "transfer-destination-request",
        "handoff-destination-request",
        "transfer-update",
        "user-interrupted",
        "voice-input",
        "chat.created",
        "chat.deleted",
        "session.created",
        "session.updated",
        "session.deleted",
        "call.deleted",
        "call.delete.failed",
        "call.artifact.upload",
    ],
    typing.Any,
]
