# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .audio_format_container import AudioFormatContainer


class AudioFormat(UncheckedBaseModel):
    sample_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="sampleRate"),
        pydantic.Field(alias="sampleRate", description="This is the sample rate of the call.\n\n@default 16000"),
    ]
    format: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    This is the audio format of the call.
    
    @default 'pcm_s16le'
    """

    container: typing.Optional[AudioFormatContainer] = pydantic.Field(default=None)
    """
    This is the container format of the call.
    
    @default 'raw'
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
