# This file was auto-generated by Fern from our API Definition.

import typing

from .board_insight_item import BoardInsightItem
from .board_metric_widget_item import BoardMetricWidgetItem

BoardItemsItem = typing.Union[BoardInsightItem, BoardMetricWidgetItem]
