# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .call_artifact_upload_item_type import CallArtifactUploadItemType


class CallArtifactUploadItem(UncheckedBaseModel):
    type: CallArtifactUploadItemType = pydantic.Field()
    """
    The artifact this result refers to.
    """

    success: bool = pydantic.Field()
    """
    Whether this artifact was stored successfully in your own configured storage.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
