# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .audio_format import AudioFormat
from .telnyx_transport_conversation_type import TelnyxTransportConversationType
from .twilio_transport_conversation_type import TwilioTransportConversationType
from .vapi_sip_transport_conversation_type import VapiSipTransportConversationType
from .vapi_web_call_transport_conversation_type import VapiWebCallTransportConversationType
from .vapi_websocket_transport_conversation_type import VapiWebsocketTransportConversationType
from .vonage_transport_conversation_type import VonageTransportConversationType


class CallTransport_VapiWebsocket(UncheckedBaseModel):
    """
    This is the transport of the call.
    """

    provider: typing.Literal["vapi.websocket"] = "vapi.websocket"
    conversation_type: typing_extensions.Annotated[
        typing.Optional[VapiWebsocketTransportConversationType],
        FieldMetadata(alias="conversationType"),
        pydantic.Field(alias="conversationType"),
    ] = None
    audio_format: typing_extensions.Annotated[
        typing.Optional[AudioFormat], FieldMetadata(alias="audioFormat"), pydantic.Field(alias="audioFormat")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CallTransport_Vonage(UncheckedBaseModel):
    """
    This is the transport of the call.
    """

    provider: typing.Literal["vonage"] = "vonage"
    conversation_type: typing_extensions.Annotated[
        typing.Optional[VonageTransportConversationType],
        FieldMetadata(alias="conversationType"),
        pydantic.Field(alias="conversationType"),
    ] = None
    conversation_uuid: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="conversationUUID"), pydantic.Field(alias="conversationUUID")
    ] = None
    call_uuid: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callUUID"), pydantic.Field(alias="callUUID")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CallTransport_Twilio(UncheckedBaseModel):
    """
    This is the transport of the call.
    """

    provider: typing.Literal["twilio"] = "twilio"
    conversation_type: typing_extensions.Annotated[
        typing.Optional[TwilioTransportConversationType],
        FieldMetadata(alias="conversationType"),
        pydantic.Field(alias="conversationType"),
    ] = None
    account_sid: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="accountSid"), pydantic.Field(alias="accountSid")
    ] = None
    call_sid: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callSid"), pydantic.Field(alias="callSid")
    ] = None
    call_token: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callToken"), pydantic.Field(alias="callToken")
    ] = None
    forwarded_from: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="forwardedFrom"), pydantic.Field(alias="forwardedFrom")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CallTransport_VapiSip(UncheckedBaseModel):
    """
    This is the transport of the call.
    """

    provider: typing.Literal["vapi.sip"] = "vapi.sip"
    conversation_type: typing_extensions.Annotated[
        typing.Optional[VapiSipTransportConversationType],
        FieldMetadata(alias="conversationType"),
        pydantic.Field(alias="conversationType"),
    ] = None
    dial_timeout: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="dialTimeout"), pydantic.Field(alias="dialTimeout")
    ] = None
    sbc_call_sid: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sbcCallSid"), pydantic.Field(alias="sbcCallSid")
    ] = None
    call_sid: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callSid"), pydantic.Field(alias="callSid")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CallTransport_Telnyx(UncheckedBaseModel):
    """
    This is the transport of the call.
    """

    provider: typing.Literal["telnyx"] = "telnyx"
    conversation_type: typing_extensions.Annotated[
        typing.Optional[TelnyxTransportConversationType],
        FieldMetadata(alias="conversationType"),
        pydantic.Field(alias="conversationType"),
    ] = None
    call_control_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callControlId"), pydantic.Field(alias="callControlId")
    ] = None
    call_leg_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callLegId"), pydantic.Field(alias="callLegId")
    ] = None
    call_session_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callSessionId"), pydantic.Field(alias="callSessionId")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CallTransport_Daily(UncheckedBaseModel):
    """
    This is the transport of the call.
    """

    provider: typing.Literal["daily"] = "daily"
    conversation_type: typing_extensions.Annotated[
        typing.Optional[VapiWebCallTransportConversationType],
        FieldMetadata(alias="conversationType"),
        pydantic.Field(alias="conversationType"),
    ] = None
    room_delete_on_user_leave_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="roomDeleteOnUserLeaveEnabled"),
        pydantic.Field(alias="roomDeleteOnUserLeaveEnabled"),
    ] = None
    call_token: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callToken"), pydantic.Field(alias="callToken")
    ] = None
    call_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callUrl"), pydantic.Field(alias="callUrl")
    ] = None
    call_sip_uri: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callSipUri"), pydantic.Field(alias="callSipUri")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CallTransport = typing_extensions.Annotated[
    typing.Union[
        CallTransport_VapiWebsocket,
        CallTransport_Vonage,
        CallTransport_Twilio,
        CallTransport_VapiSip,
        CallTransport_Telnyx,
        CallTransport_Daily,
    ],
    UnionMetadata(discriminant="provider"),
]
