# This file was auto-generated by Fern from our API Definition.

import typing

CampaignSummaryServerMessagesItem = typing.Union[
    typing.Literal[
        "campaign.started",
        "campaign.cancelled",
        "campaign.ended",
        "campaign.archived",
        "campaign.unarchived",
        "contact.dispatched",
        "contact.completed",
        "contact.failed",
        "contact.skipped",
        "contact.predial-failed",
        "campaign.job.continued",
    ],
    typing.Any,
]
