# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class CampaignCallMetrics(UncheckedBaseModel):
    dialed: float = pydantic.Field()
    """
    This is the number of contacts a call was actually placed for. Contacts
    that were skipped, rejected before dialing, or failed to dispatch are not
    counted — no call existed, so there was nothing to answer.
    """

    connected: float = pydantic.Field()
    """
    This is the number of those calls a human picked up. Voicemail does not
    count. Divide by `dialed` for the pick-up rate.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
