# This file was auto-generated by Fern from our API Definition.

import typing

ClientInboundMessageAppendContextKind = typing.Union[
    typing.Literal["commentary", "thinking", "instructions"], typing.Any
]
