# This file was auto-generated by Fern from our API Definition.

import typing

CreateElevenLabsCredentialDtoApiUrl = typing.Union[
    typing.Literal["https://api.elevenlabs.io", "https://api.eu.residency.elevenlabs.io"], typing.Any
]
