# This file was auto-generated by Fern from our API Definition.

import typing

from .create_assistant_draft_dto_voicemail_detection_zero import CreateAssistantDraftDtoVoicemailDetectionZero
from .google_voicemail_detection_plan import GoogleVoicemailDetectionPlan
from .open_ai_voicemail_detection_plan import OpenAiVoicemailDetectionPlan
from .twilio_voicemail_detection_plan import TwilioVoicemailDetectionPlan
from .vapi_voicemail_detection_plan import VapiVoicemailDetectionPlan

CreateAssistantDraftDtoVoicemailDetection = typing.Union[
    CreateAssistantDraftDtoVoicemailDetectionZero,
    GoogleVoicemailDetectionPlan,
    OpenAiVoicemailDetectionPlan,
    TwilioVoicemailDetectionPlan,
    VapiVoicemailDetectionPlan,
]
