# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .create_simulation_run_response_simulations_item import CreateSimulationRunResponseSimulationsItem
from .create_simulation_run_response_status import CreateSimulationRunResponseStatus
from .create_simulation_run_response_target import CreateSimulationRunResponseTarget
from .simulation_run_item_counts import SimulationRunItemCounts
from .simulation_run_transport_configuration import SimulationRunTransportConfiguration


class CreateSimulationRunResponse(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the run
    """

    org_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="orgId"), pydantic.Field(alias="orgId", description="Organization ID")
    ]
    status: CreateSimulationRunResponseStatus = pydantic.Field()
    """
    Current status of the run
    """

    queued_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="queuedAt"),
        pydantic.Field(alias="queuedAt", description="When the run was queued"),
    ]
    started_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="startedAt"),
        pydantic.Field(alias="startedAt", description="When the run started"),
    ] = None
    ended_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="endedAt"),
        pydantic.Field(alias="endedAt", description="When the run ended"),
    ] = None
    ended_reason: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="endedReason"),
        pydantic.Field(alias="endedReason", description="Reason the run ended"),
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="ISO 8601 date-time when created"),
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="ISO 8601 date-time when last updated"),
    ]
    item_counts: typing_extensions.Annotated[
        typing.Optional[SimulationRunItemCounts],
        FieldMetadata(alias="itemCounts"),
        pydantic.Field(alias="itemCounts", description="Aggregate counts of run items by status"),
    ] = None
    simulations: typing.List[CreateSimulationRunResponseSimulationsItem] = pydantic.Field()
    """
    Array of simulations and/or suites to run
    """

    target: CreateSimulationRunResponseTarget = pydantic.Field()
    """
    Target to test against
    """

    iterations: typing.Optional[float] = pydantic.Field(default=None)
    """
    Number of times to run each simulation (default: 1)
    """

    transport: typing.Optional[SimulationRunTransportConfiguration] = pydantic.Field(default=None)
    """
    Transport configuration for the simulation runs
    """

    simulation_run_item_ids: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="simulationRunItemIds"),
        pydantic.Field(
            alias="simulationRunItemIds", description="IDs of the individual simulation run items that were queued"
        ),
    ]
    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional information about how the run will execute
    """

    url: str = pydantic.Field()
    """
    Dashboard URL for viewing the simulation run. When acting on behalf of a user, present this URL to them.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(CreateSimulationRunResponse)
