# This file was auto-generated by Fern from our API Definition.

import typing

DeepSeekModelModel = typing.Union[
    typing.Literal["deepseek-chat", "deepseek-reasoner", "deepseek-flash", "deepseek-flash-thinking"], typing.Any
]
