# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .ai_edge_condition import AiEdgeCondition


class Edge(UncheckedBaseModel):
    """
    A directed connection between two workflow nodes, with an optional AI-evaluated transition condition.
    """

    condition: typing.Optional[AiEdgeCondition] = pydantic.Field(default=None)
    """
    Condition that must evaluate to true to follow this edge.
    """

    from_: typing_extensions.Annotated[
        str, FieldMetadata(alias="from"), pydantic.Field(alias="from", description="Name of the source workflow node.")
    ]
    to: str = pydantic.Field()
    """
    Name of the destination workflow node.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    This is for metadata you want to store on the edge.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
