# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .eleven_labs_credential_api_url import ElevenLabsCredentialApiUrl


class ElevenLabsCredential(UncheckedBaseModel):
    provider: typing.Literal["11labs"] = "11labs"
    api_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="apiKey"),
        pydantic.Field(alias="apiKey", description="This is not returned in the API."),
    ]
    api_url: typing_extensions.Annotated[
        typing.Optional[ElevenLabsCredentialApiUrl],
        FieldMetadata(alias="apiUrl"),
        pydantic.Field(
            alias="apiUrl",
            description="ElevenLabs-only API environment for this key: the global endpoint or the EU data residency endpoint. In EU deployments, new credentials must explicitly use the EU data residency endpoint; existing credentials may omit this field on update to retain their saved endpoint. Outside EU deployments, Vapi detects an omitted endpoint automatically and null on update clears and re-detects the endpoint.",
        ),
    ] = None
    id: str = pydantic.Field()
    """
    This is the unique identifier for the credential.
    """

    org_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="orgId"),
        pydantic.Field(
            alias="orgId", description="This is the unique identifier for the org that this credential belongs to."
        ),
    ]
    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt", description="This is the ISO 8601 date-time string of when the credential was created."
        ),
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(
            alias="updatedAt",
            description="This is the ISO 8601 date-time string of when the assistant was last updated.",
        ),
    ]
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    This is the name of credential. This is just for your reference.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
