# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .fallback_transcriber_plan_transcribers_item import FallbackTranscriberPlanTranscribersItem


class FallbackTranscriberPlan(UncheckedBaseModel):
    """
    Lists backup transcriber configurations that can be used if the primary transcriber fails.
    """

    transcribers: typing.Optional[typing.List[FallbackTranscriberPlanTranscribersItem]] = pydantic.Field(default=None)
    """
    Transcriber configurations available when the primary transcriber fails.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
