# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .fallback_cartesia_transcriber_language import FallbackCartesiaTranscriberLanguage
from .fallback_cartesia_transcriber_model import FallbackCartesiaTranscriberModel


class FallbackCartesiaTranscriber(UncheckedBaseModel):
    """
    Fallback configuration for transcribing speech with Cartesia, including model and language.
    """

    model: typing.Optional[FallbackCartesiaTranscriberModel] = pydantic.Field(default=None)
    """
    The Cartesia speech-to-text model used for transcription.
    """

    language: typing.Optional[FallbackCartesiaTranscriberLanguage] = pydantic.Field(default=None)
    """
    The language code used for transcription.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
