# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .chunk_plan import ChunkPlan
from .fallback_xai_voice_language import FallbackXaiVoiceLanguage
from .fallback_xai_voice_voice_id import FallbackXaiVoiceVoiceId


class FallbackXaiVoice(UncheckedBaseModel):
    caching_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="cachingEnabled"),
        pydantic.Field(
            alias="cachingEnabled", description="This is the flag to toggle voice caching for the assistant."
        ),
    ] = None
    voice_id: typing_extensions.Annotated[
        FallbackXaiVoiceVoiceId,
        FieldMetadata(alias="voiceId"),
        pydantic.Field(
            alias="voiceId", description="Built-in voices: eve, ara, rex, sal, leo. Cloned voice IDs are also accepted."
        ),
    ]
    language: typing.Optional[FallbackXaiVoiceLanguage] = pydantic.Field(default=None)
    """
    BCP-47 language code for xAI TTS synthesis.
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speed multiplier for xAI TTS synthesis.
    """

    chunk_plan: typing_extensions.Annotated[
        typing.Optional[ChunkPlan],
        FieldMetadata(alias="chunkPlan"),
        pydantic.Field(
            alias="chunkPlan",
            description="This is the plan for chunking the model output before it is sent to the voice provider.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
