# This file was auto-generated by Fern from our API Definition.

import typing

from .fallback_azure_voice_id_zero import FallbackAzureVoiceIdZero

FallbackAzureVoiceId = typing.Union[FallbackAzureVoiceIdZero, str]
