# This file was auto-generated by Fern from our API Definition.

import typing

FallbackMicrosoftVoiceStyle = typing.Union[
    typing.Literal[
        "adventurous",
        "angry",
        "caring",
        "cheerful",
        "confused",
        "curious",
        "determined",
        "disappointed",
        "disgusted",
        "embarrassed",
        "empathy",
        "encouraging",
        "excited",
        "fearful",
        "friendly",
        "happy",
        "hopeful",
        "jealous",
        "joyful",
        "nostalgic",
        "reflective",
        "regretful",
        "relieved",
        "sad",
        "serious",
        "shouting",
        "softvoice",
        "surprised",
        "whispering",
    ],
    typing.Any,
]
