# This file was auto-generated by Fern from our API Definition.

import typing

FallbackXaiTranscriberLanguage = typing.Union[
    typing.Literal[
        "ar",
        "cs",
        "da",
        "nl",
        "en",
        "fil",
        "fr",
        "de",
        "hi",
        "id",
        "it",
        "ja",
        "ko",
        "mk",
        "ms",
        "fa",
        "pl",
        "pt",
        "ro",
        "ru",
        "es",
        "sv",
        "th",
        "tr",
        "vi",
    ],
    typing.Any,
]
