# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class GetToolDraftsDto(UncheckedBaseModel):
    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque base64-encoded keyset cursor. Omit on first page.
    """

    limit: typing.Optional[float] = pydantic.Field(default=None)
    """
    Page size, defaults to 25, capped at 100.
    """

    created_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="createdBy"), pydantic.Field(alias="createdBy")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
