# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class GhlToolMetadata(UncheckedBaseModel):
    """
    GHL workflow and location identifiers attached to a tool.
    """

    workflow_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="workflowId"),
        pydantic.Field(alias="workflowId", description="GHL workflow identifier associated with the tool."),
    ] = None
    location_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="locationId"),
        pydantic.Field(alias="locationId", description="GHL location identifier associated with the tool."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
