# This file was auto-generated by Fern from our API Definition.

import typing

MicrosoftVoiceRole = typing.Union[
    typing.Literal[
        "Girl",
        "Boy",
        "YoungAdultFemale",
        "YoungAdultMale",
        "OlderAdultFemale",
        "OlderAdultMale",
        "SeniorFemale",
        "SeniorMale",
    ],
    typing.Any,
]
