# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .model_deprecation_notice_replacement_status import ModelDeprecationNoticeReplacementStatus


class ModelDeprecationNotice(UncheckedBaseModel):
    slot: str = pydantic.Field()
    """
    Path of the slot that carries the model, relative to the response root,
    e.g. `model`, `model.fallbackModels[1]`, `transcriber`, `voice`, or
    `members[2].assistantOverrides.model` on a squad.
    """

    provider: str = pydantic.Field()
    """
    Provider as stored on the slot.
    """

    model: str = pydantic.Field()
    """
    Model name as stored on the slot.
    """

    deprecation_date: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="deprecationDate"),
        pydantic.Field(alias="deprecationDate", description="Day the model became deprecated, `YYYY-MM-DD` in UTC."),
    ]
    retirement_date: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="retirementDate"),
        pydantic.Field(
            alias="retirementDate",
            description="Day the model is or was retired, `YYYY-MM-DD` in UTC. On and after this\nday Vapi no longer runs the model as configured.",
        ),
    ]
    replacement_status: typing_extensions.Annotated[
        ModelDeprecationNoticeReplacementStatus,
        FieldMetadata(alias="replacementStatus"),
        pydantic.Field(
            alias="replacementStatus", description="Whether a replacement can be recommended for this configuration."
        ),
    ]
    replacement_model: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="replacementModel"),
        pydantic.Field(
            alias="replacementModel",
            description="Recommended model when replacementStatus is available. Omitted when\neligibility cannot be established or no eligible replacement exists.\nA recommendation reflects the response-time decision; it neither\nconfirms a completed swap nor authorizes a future execution.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
