# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class MonitorPlan(UncheckedBaseModel):
    """
    Controls real-time listening and control for assistant calls, authentication requirements for monitor URLs, and attached monitors.
    """

    listen_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="listenEnabled"),
        pydantic.Field(
            alias="listenEnabled",
            description="This determines whether the assistant's calls allow live listening. Defaults to true.\n\nFetch `call.monitor.listenUrl` to get the live listening URL.\n\n@default true",
        ),
    ] = None
    listen_authentication_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="listenAuthenticationEnabled"),
        pydantic.Field(
            alias="listenAuthenticationEnabled",
            description="This enables authentication on the `call.monitor.listenUrl`.\n\nIf `listenAuthenticationEnabled` is `true`, the `call.monitor.listenUrl` will require an `Authorization: Bearer <vapi-public-api-key>` header.\n\n@default false",
        ),
    ] = None
    control_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="controlEnabled"),
        pydantic.Field(
            alias="controlEnabled",
            description="This determines whether the assistant's calls allow live control. Defaults to true.\n\nFetch `call.monitor.controlUrl` to get the live control URL.\n\nTo use, send any control message via a POST request to `call.monitor.controlUrl`. Here are the types of controls supported: https://docs.vapi.ai/api-reference/messages/client-inbound-message\n\n@default true",
        ),
    ] = None
    control_authentication_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="controlAuthenticationEnabled"),
        pydantic.Field(
            alias="controlAuthenticationEnabled",
            description="This enables authentication on the `call.monitor.controlUrl`.\n\nIf `controlAuthenticationEnabled` is `true`, the `call.monitor.controlUrl` will require an `Authorization: Bearer <vapi-public-api-key>` header.\n\n@default false",
        ),
    ] = None
    monitor_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="monitorIds"),
        pydantic.Field(
            alias="monitorIds",
            description="IDs of the monitors attached to the assistant. Use this field for transient assistants or to update the monitors attached to an existing assistant. Defaults to an empty array.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
