# This file was auto-generated by Fern from our API Definition.

import typing

NumberComparatorScorecardMetricConditionComparator = typing.Union[
    typing.Literal["=", "!=", ">", "<", ">=", "<="], typing.Any
]
