# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .open_ai_reasoner_skill_tools_item import OpenAiReasonerSkillToolsItem


class OpenAiReasonerSkill(UncheckedBaseModel):
    name: str = pydantic.Field()
    """
    Unique name within this assistant.
    """

    description: str = pydantic.Field()
    """
    Explain when the reasoner should load this skill. Always visible in its catalog.
    """

    content: str = pydantic.Field()
    """
    Full skill instructions, loaded only while this skill is active.
    """

    tools: typing.Optional[typing.List[OpenAiReasonerSkillToolsItem]] = pydantic.Field(default=None)
    """
    Tools available only after loading this skill. Can be combined with toolIds.
    """

    tool_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="toolIds"),
        pydantic.Field(
            alias="toolIds", description="Existing organization-owned tools available only after loading this skill."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(OpenAiReasonerSkill)
