# This file was auto-generated by Fern from our API Definition.

import typing

OpenAiModelReasoningEffort = typing.Union[
    typing.Literal["minimal", "none", "low", "medium", "high", "xhigh"], typing.Any
]
