# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .open_ai_speaker_personality_packs_item import OpenAiSpeakerPersonalityPacksItem


class OpenAiSpeaker(UncheckedBaseModel):
    instructions: typing.Optional[str] = pydantic.Field(default=None)
    """
    Omit to use model.systemPrompt, or system-role messages when systemPrompt is absent. An explicit empty string is preserved.
    """

    personality_packs: typing_extensions.Annotated[
        typing.Optional[typing.List[OpenAiSpeakerPersonalityPacksItem]],
        FieldMetadata(alias="personalityPacks"),
        pydantic.Field(
            alias="personalityPacks",
            description="Personality packs append speaking-style guidance to the speaker prompt. Set to an array of pack IDs and test one pack at a time. These are prompt instructions, not fixed speed controls.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
