# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .backoff_plan import BackoffPlan
from .create_api_request_tool_dto_messages_item import CreateApiRequestToolDtoMessagesItem
from .create_api_request_tool_dto_method import CreateApiRequestToolDtoMethod
from .create_dtmf_tool_dto_messages_item import CreateDtmfToolDtoMessagesItem
from .create_end_call_tool_dto_messages_item import CreateEndCallToolDtoMessagesItem
from .create_function_tool_dto_messages_item import CreateFunctionToolDtoMessagesItem
from .create_mcp_tool_dto_messages_item import CreateMcpToolDtoMessagesItem
from .create_transfer_call_tool_dto_destinations_item import CreateTransferCallToolDtoDestinationsItem
from .create_transfer_call_tool_dto_messages_item import CreateTransferCallToolDtoMessagesItem
from .mcp_tool_messages import McpToolMessages
from .mcp_tool_metadata import McpToolMetadata
from .open_ai_function import OpenAiFunction
from .server import Server
from .tool_parameter import ToolParameter
from .tool_rejection_plan import ToolRejectionPlan
from .variable_extraction_plan import VariableExtractionPlan


class OpenAiReasonerSkillToolsItem_Function(UncheckedBaseModel):
    type: typing.Literal["function"] = "function"
    messages: typing.Optional[typing.List[CreateFunctionToolDtoMessagesItem]] = None
    async_: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="async"), pydantic.Field(alias="async")
    ] = None
    server: typing.Optional[Server] = None
    variable_extraction_plan: typing_extensions.Annotated[
        typing.Optional[VariableExtractionPlan],
        FieldMetadata(alias="variableExtractionPlan"),
        pydantic.Field(alias="variableExtractionPlan"),
    ] = None
    parameters: typing.Optional[typing.List[ToolParameter]] = None
    function: typing.Optional[OpenAiFunction] = None
    rejection_plan: typing_extensions.Annotated[
        typing.Optional[ToolRejectionPlan], FieldMetadata(alias="rejectionPlan"), pydantic.Field(alias="rejectionPlan")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class OpenAiReasonerSkillToolsItem_ApiRequest(UncheckedBaseModel):
    type: typing.Literal["apiRequest"] = "apiRequest"
    messages: typing.Optional[typing.List[CreateApiRequestToolDtoMessagesItem]] = None
    name: typing.Optional[str] = None
    method: CreateApiRequestToolDtoMethod
    timeout_seconds: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="timeoutSeconds"), pydantic.Field(alias="timeoutSeconds")
    ] = None
    credential_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="credentialId"), pydantic.Field(alias="credentialId")
    ] = None
    encrypted_paths: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="encryptedPaths"), pydantic.Field(alias="encryptedPaths")
    ] = None
    parameters: typing.Optional[typing.List[ToolParameter]] = None
    description: typing.Optional[str] = None
    url: str
    body: typing.Optional["JsonSchema"] = None
    headers: typing.Optional["JsonSchema"] = None
    backoff_plan: typing_extensions.Annotated[
        typing.Optional[BackoffPlan], FieldMetadata(alias="backoffPlan"), pydantic.Field(alias="backoffPlan")
    ] = None
    variable_extraction_plan: typing_extensions.Annotated[
        typing.Optional[VariableExtractionPlan],
        FieldMetadata(alias="variableExtractionPlan"),
        pydantic.Field(alias="variableExtractionPlan"),
    ] = None
    rejection_plan: typing_extensions.Annotated[
        typing.Optional[ToolRejectionPlan], FieldMetadata(alias="rejectionPlan"), pydantic.Field(alias="rejectionPlan")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class OpenAiReasonerSkillToolsItem_Mcp(UncheckedBaseModel):
    type: typing.Literal["mcp"] = "mcp"
    messages: typing.Optional[typing.List[CreateMcpToolDtoMessagesItem]] = None
    server: typing.Optional[Server] = None
    tool_messages: typing_extensions.Annotated[
        typing.Optional[typing.List[McpToolMessages]],
        FieldMetadata(alias="toolMessages"),
        pydantic.Field(alias="toolMessages"),
    ] = None
    metadata: typing.Optional[McpToolMetadata] = None
    rejection_plan: typing_extensions.Annotated[
        typing.Optional[ToolRejectionPlan], FieldMetadata(alias="rejectionPlan"), pydantic.Field(alias="rejectionPlan")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class OpenAiReasonerSkillToolsItem_EndCall(UncheckedBaseModel):
    type: typing.Literal["endCall"] = "endCall"
    messages: typing.Optional[typing.List[CreateEndCallToolDtoMessagesItem]] = None
    rejection_plan: typing_extensions.Annotated[
        typing.Optional[ToolRejectionPlan], FieldMetadata(alias="rejectionPlan"), pydantic.Field(alias="rejectionPlan")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class OpenAiReasonerSkillToolsItem_Dtmf(UncheckedBaseModel):
    type: typing.Literal["dtmf"] = "dtmf"
    messages: typing.Optional[typing.List[CreateDtmfToolDtoMessagesItem]] = None
    sip_info_dtmf_enabled: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="sipInfoDtmfEnabled"), pydantic.Field(alias="sipInfoDtmfEnabled")
    ] = None
    rejection_plan: typing_extensions.Annotated[
        typing.Optional[ToolRejectionPlan], FieldMetadata(alias="rejectionPlan"), pydantic.Field(alias="rejectionPlan")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class OpenAiReasonerSkillToolsItem_TransferCall(UncheckedBaseModel):
    type: typing.Literal["transferCall"] = "transferCall"
    messages: typing.Optional[typing.List[CreateTransferCallToolDtoMessagesItem]] = None
    destinations: typing.Optional[typing.List[CreateTransferCallToolDtoDestinationsItem]] = None
    rejection_plan: typing_extensions.Annotated[
        typing.Optional[ToolRejectionPlan], FieldMetadata(alias="rejectionPlan"), pydantic.Field(alias="rejectionPlan")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


OpenAiReasonerSkillToolsItem = typing_extensions.Annotated[
    typing.Union[
        OpenAiReasonerSkillToolsItem_Function,
        OpenAiReasonerSkillToolsItem_ApiRequest,
        OpenAiReasonerSkillToolsItem_Mcp,
        OpenAiReasonerSkillToolsItem_EndCall,
        OpenAiReasonerSkillToolsItem_Dtmf,
        OpenAiReasonerSkillToolsItem_TransferCall,
    ],
    UnionMetadata(discriminant="type"),
]
from .json_schema import JsonSchema  # noqa: E402, I001

update_forward_refs(OpenAiReasonerSkillToolsItem_Function)
update_forward_refs(OpenAiReasonerSkillToolsItem_ApiRequest, JsonSchema=JsonSchema)
update_forward_refs(OpenAiReasonerSkillToolsItem_Mcp)
update_forward_refs(OpenAiReasonerSkillToolsItem_EndCall)
update_forward_refs(OpenAiReasonerSkillToolsItem_Dtmf)
update_forward_refs(OpenAiReasonerSkillToolsItem_TransferCall)
