# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class OrgApiLimitsDto(UncheckedBaseModel):
    rate_limit_usage: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="rateLimitUsage"),
        pydantic.Field(
            alias="rateLimitUsage",
            description="Approximate number of API requests counted against the rate limit in the current minute, in the region that served this request. The count lives in a tumbling one-minute window aligned to the UTC clock (unix seconds / 60), so it resets to zero at the top of every minute; there is no reset header — the next boundary is (floor(now / 60) + 1) * 60.",
        ),
    ]
    rate_limit_max: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="rateLimitMax"),
        pydantic.Field(
            alias="rateLimitMax",
            description="Maximum number of standard API requests allowed per minute, in the region that served this request. Live call media traffic is limited separately and is not reflected here.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
