# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .org_api_limits_dto import OrgApiLimitsDto
from .org_concurrency_limits_dto import OrgConcurrencyLimitsDto


class OrgLimitsResponseDto(UncheckedBaseModel):
    subscription_limits: typing_extensions.Annotated[
        typing.Optional[OrgConcurrencyLimitsDto],
        FieldMetadata(alias="subscriptionLimits"),
        pydantic.Field(
            alias="subscriptionLimits",
            description="Call concurrency limits for the subscription. Unlike the call create response, remainingConcurrentCalls does not reserve a slot for a new call: it is the plain headroom at the time of the read. Covers the concurrency gate only — credits, frozen subscriptions, included minutes, and the billing limit are not reflected here, so call create can still refuse. Omitted when the limits could not be computed, and for an org with no subscription at all (legacy ungated orgs), which has no concurrency ceiling.",
        ),
    ] = None
    api_limits: typing_extensions.Annotated[
        typing.Optional[OrgApiLimitsDto],
        FieldMetadata(alias="apiLimits"),
        pydantic.Field(
            alias="apiLimits",
            description="API rate limit usage for the org. Approximate, per region, and scoped to the current minute. Omitted when the limit information is unavailable.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
