# This file was auto-generated by Fern from our API Definition.

import typing

RecordingConsentPlanVerbalFirstMessageMode = typing.Union[
    typing.Literal["assistant-speaks-first", "assistant-waits-for-user"], typing.Any
]
