# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .recording_consent_plan_stay_on_line_first_message_mode import RecordingConsentPlanStayOnLineFirstMessageMode
from .recording_consent_plan_stay_on_line_voice import RecordingConsentPlanStayOnLineVoice


class RecordingConsentPlanStayOnLine(UncheckedBaseModel):
    """
    Configuration for requesting recording consent by treating continued presence on the call as consent, including the announcement voice and wait time.
    """

    message: str = pydantic.Field()
    """
    This is the message asking for consent to record the call.
    If the type is `stay-on-line`, the message should ask the user to hang up if they do not consent.
    If the type is `verbal`, the message should ask the user to verbally consent or decline.
    """

    voice: typing.Optional[RecordingConsentPlanStayOnLineVoice] = pydantic.Field(default=None)
    """
    This is the voice to use for the consent message. If not specified, inherits from the assistant's voice.
    Use a different voice for the consent message for a better user experience.
    """

    first_message_mode: typing_extensions.Annotated[
        typing.Optional[RecordingConsentPlanStayOnLineFirstMessageMode],
        FieldMetadata(alias="firstMessageMode"),
        pydantic.Field(
            alias="firstMessageMode",
            description="This controls whether the consent assistant speaks first or waits for the caller to speak first.\n\nUse:\n- `assistant-speaks-first` (default) to have the consent assistant play the consent message as soon as the call is answered.\n- `assistant-waits-for-user` to have the consent assistant wait for the caller to speak before playing the consent message.\n\nWe strongly recommend `assistant-waits-for-user` for outbound calls. Some telephony providers signal \"answered\" while the line is still ringing, which can cause the consent message to play into a ringing line and be missed by the caller. Waiting for the caller to speak first guarantees they hear the full consent message.\n\nNote: when combined with `type: 'stay-on-line'`, silence only counts toward consent after the caller has spoken at least once.\n\n@default 'assistant-speaks-first'",
        ),
    ] = None
    wait_seconds: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="waitSeconds"),
        pydantic.Field(
            alias="waitSeconds",
            description="Number of seconds to wait before transferring to the assistant if user stays on the call",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
