# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .say_hook_action_exact import SayHookActionExact
from .say_hook_action_prompt import SayHookActionPrompt


class SayHookAction(UncheckedBaseModel):
    """
    A hook action that makes the assistant speak exact text or generate a response from a prompt.
    """

    exact: typing.Optional[SayHookActionExact] = pydantic.Field(default=None)
    """
    This is the exact message to say. When a string array is provided, one is randomly selected.
    """

    prompt: typing.Optional[SayHookActionPrompt] = pydantic.Field(default=None)
    """
    This is the prompt for the assistant to generate a response based on existing conversation.
    Can be a string or an array of chat messages.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
