# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class ScenarioToolMock(UncheckedBaseModel):
    tool_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="toolName"),
        pydantic.Field(
            alias="toolName",
            description="The name of the assistant or squad's tool to mock. Must match the tool's name exactly.",
        ),
    ]
    result: typing.Optional[str] = pydantic.Field(default=None)
    """
    The result string returned to the assistant or squad in place of calling the real tool.
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Set to `true` to apply this mock during the simulation. Defaults to `true`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
