# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .pagination_meta import PaginationMeta
from .scorecard import Scorecard


class ScorecardPaginatedResponse(UncheckedBaseModel):
    """
    A paginated collection of scorecards and metadata describing the result set.
    """

    results: typing.List[Scorecard] = pydantic.Field()
    """
    The scorecards returned for the current page.
    """

    metadata: PaginationMeta = pydantic.Field()
    """
    Pagination metadata for the scorecard result set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
