# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .simulation_run_configuration import SimulationRunConfiguration
from .simulation_run_item_hooks_item import SimulationRunItemHooksItem
from .simulation_run_item_improvements import SimulationRunItemImprovements
from .simulation_run_item_metadata import SimulationRunItemMetadata
from .simulation_run_item_results import SimulationRunItemResults
from .simulation_run_item_status import SimulationRunItemStatus


class SimulationRunItem(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    This is the unique identifier for the simulation run item.
    """

    org_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="orgId"),
        pydantic.Field(alias="orgId", description="This is the unique identifier for the organization."),
    ]
    simulation_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="simulationId"),
        pydantic.Field(alias="simulationId", description="This is the ID of the simulation this run belongs to."),
    ]
    status: SimulationRunItemStatus = pydantic.Field()
    """
    The run item's current status.
    """

    queued_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="queuedAt"),
        pydantic.Field(
            alias="queuedAt", description="This is the ISO 8601 date-time string of when the run was queued."
        ),
    ]
    started_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="startedAt"),
        pydantic.Field(alias="startedAt", description="This is the ISO 8601 date-time string of when the run started."),
    ] = None
    completed_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="completedAt"),
        pydantic.Field(
            alias="completedAt", description="This is the ISO 8601 date-time string of when the run completed."
        ),
    ] = None
    failed_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="failedAt"),
        pydantic.Field(alias="failedAt", description="This is the ISO 8601 date-time string of when the run failed."),
    ] = None
    canceled_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="canceledAt"),
        pydantic.Field(
            alias="canceledAt", description="This is the ISO 8601 date-time string of when the run was canceled."
        ),
    ] = None
    failure_reason: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="failureReason"),
        pydantic.Field(alias="failureReason", description="Why the run item failed, when applicable."),
    ] = None
    call_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="callId"),
        pydantic.Field(alias="callId", description="The ID of the call that ran this item."),
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt", description="This is the ISO 8601 date-time string of when the run item was created."
        ),
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(
            alias="updatedAt",
            description="This is the ISO 8601 date-time string of when the run item was last updated.",
        ),
    ]
    run_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="runId"),
        pydantic.Field(alias="runId", description="This is the ID of the parent run (batch/group)."),
    ] = None
    hooks: typing.Optional[typing.List[SimulationRunItemHooksItem]] = pydantic.Field(default=None)
    """
    Hooks configured for this simulation run item
    """

    iteration_number: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="iterationNumber"),
        pydantic.Field(alias="iterationNumber", description="Which iteration of the simulation this item represents."),
    ] = None
    session_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="sessionId"),
        pydantic.Field(
            alias="sessionId", description="This is the session ID for chat-based simulations (webchat transport)."
        ),
    ] = None
    scenario_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="scenarioId"),
        pydantic.Field(alias="scenarioId", description="The ID of the scenario used for this run item."),
    ] = None
    personality_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="personalityId"),
        pydantic.Field(alias="personalityId", description="The ID of the personality used for this run item."),
    ] = None
    metadata: typing.Optional[SimulationRunItemMetadata] = pydantic.Field(default=None)
    """
    This is the metadata containing snapshots and call data.
    """

    results: typing.Optional[SimulationRunItemResults] = pydantic.Field(default=None)
    """
    The evaluation results for this run item.
    """

    improvement_suggestions: typing_extensions.Annotated[
        typing.Optional[SimulationRunItemImprovements],
        FieldMetadata(alias="improvementSuggestions"),
        pydantic.Field(
            alias="improvementSuggestions",
            description="AI-generated suggestions for improving the assistant or squad's system prompt, tools, and scenarios after a failed run.",
        ),
    ] = None
    configurations: typing.Optional[SimulationRunConfiguration] = pydantic.Field(default=None)
    """
    This is the configuration for how this simulation run executes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(SimulationRunItem)
