# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class StructuredOutputCostBreakdown(UncheckedBaseModel):
    structured_output_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="structuredOutputId"),
        pydantic.Field(
            alias="structuredOutputId",
            description="This is the unique identifier of the structured output that produced this cost.",
        ),
    ]
    name: str = pydantic.Field()
    """
    This is the name of the structured output, so this breakdown is readable without looking the id up.
    """

    cost: float = pydantic.Field()
    """
    This is the cost in USD of evaluating this structured output.
    """

    prompt_tokens: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="promptTokens"),
        pydantic.Field(
            alias="promptTokens",
            description="This is the number of prompt tokens used to evaluate this structured output.",
        ),
    ]
    completion_tokens: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="completionTokens"),
        pydantic.Field(
            alias="completionTokens",
            description="This is the number of completion tokens generated for this structured output.",
        ),
    ]
    cached_prompt_tokens: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="cachedPromptTokens"),
        pydantic.Field(
            alias="cachedPromptTokens",
            description="This is the number of cached prompt tokens used to evaluate this structured output. This is a subset of `promptTokens`, not an addition to it.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
