# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .ended_reason_condition_operator import EndedReasonConditionOperator


class StructuredOutputConditionsItem_MinMessages(UncheckedBaseModel):
    type: typing.Literal["minMessages"] = "minMessages"
    count: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class StructuredOutputConditionsItem_MinCallDuration(UncheckedBaseModel):
    type: typing.Literal["minCallDuration"] = "minCallDuration"
    seconds: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class StructuredOutputConditionsItem_EndedReason(UncheckedBaseModel):
    type: typing.Literal["endedReason"] = "endedReason"
    operator: EndedReasonConditionOperator
    values: typing.List[str]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


StructuredOutputConditionsItem = typing_extensions.Annotated[
    typing.Union[
        StructuredOutputConditionsItem_MinMessages,
        StructuredOutputConditionsItem_MinCallDuration,
        StructuredOutputConditionsItem_EndedReason,
    ],
    UnionMetadata(discriminant="type"),
]
