# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.unchecked_base_model import UncheckedBaseModel
from .tool_draft import ToolDraft
from .tool_draft_paginated_metadata import ToolDraftPaginatedMetadata


class ToolDraftPaginatedResponse(UncheckedBaseModel):
    results: typing.List[ToolDraft]
    metadata: ToolDraftPaginatedMetadata

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(ToolDraftPaginatedResponse)
