# This file was auto-generated by Fern from our API Definition.

import typing

ToolDraftType = typing.Union[
    typing.Literal[
        "dtmf",
        "endCall",
        "knowledgeBase",
        "transferCall",
        "transferCancel",
        "transferSuccessful",
        "handoff",
        "output",
        "voicemail",
        "query",
        "sms",
        "sipRequest",
        "function",
        "mcp",
        "apiRequest",
        "code",
        "bash",
        "computer",
        "textEditor",
        "google.calendar.event.create",
        "google.calendar.availability.check",
        "google.sheets.row.append",
        "slack.message.send",
        "gohighlevel.calendar.event.create",
        "gohighlevel.calendar.availability.check",
        "gohighlevel.contact.create",
        "gohighlevel.contact.get",
        "make",
        "ghl",
    ],
    typing.Any,
]
