# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class TrafficAllocationTarget(UncheckedBaseModel):
    assistant_version: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="assistantVersion"),
        pydantic.Field(
            alias="assistantVersion", description='The assistant version this target sends calls to, such as "v7".'
        ),
    ]
    position: float = pydantic.Field()
    """
    The target's place in the split, starting at 0. Set from the order of the targets array.
    """

    percentage: float = pydantic.Field()
    """
    Share of calls sent to this version, from 0 to 100 with up to three decimal places. Targets add up to exactly 100. A 0% target keeps the version in the split without sending it calls.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
