# This file was auto-generated by Fern from our API Definition.

import typing

TransferArtifactStatus = typing.Union[
    typing.Literal["connected", "no-answer", "busy", "voicemail", "failed", "completed", "cancelled"], typing.Any
]
