# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .dial_plan_entry import DialPlanEntry
from .schedule_plan import SchedulePlan
from .update_campaign_dto_status import UpdateCampaignDtoStatus


class UpdateCampaignDto(UncheckedBaseModel):
    """
    Fields used to update an outbound calling campaign, including its name, status, calling resource, phone-number or dial-plan settings, and schedule.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    This is the name of the campaign. This is just for your own reference.
    """

    assistant_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="assistantId"),
        pydantic.Field(
            alias="assistantId",
            description="This is the assistant ID that will be used for the campaign calls.\nCan only be updated if campaign is not in progress or has ended.",
        ),
    ] = None
    workflow_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="workflowId"),
        pydantic.Field(
            alias="workflowId",
            description="This is the workflow ID that will be used for the campaign calls.\nCan only be updated if campaign is not in progress or has ended.",
        ),
    ] = None
    squad_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="squadId"),
        pydantic.Field(
            alias="squadId",
            description="This is the squad ID that will be used for the campaign calls.\nCan only be updated if campaign is not in progress or has ended.",
        ),
    ] = None
    phone_number_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="phoneNumberId"),
        pydantic.Field(
            alias="phoneNumberId",
            description="This is the phone number ID that will be used for the campaign calls.\nCan only be updated if campaign is not in progress or has ended.\nNote: `phoneNumberId` and `dialPlan` are mutually exclusive.",
        ),
    ] = None
    dial_plan: typing_extensions.Annotated[
        typing.Optional[typing.List[DialPlanEntry]],
        FieldMetadata(alias="dialPlan"),
        pydantic.Field(
            alias="dialPlan",
            description="This is a list of dial entries, each specifying a phone number and the customers to call using that number. Can only be updated if campaign is not in progress or has ended. Note: phoneNumberId and dialPlan are mutually exclusive.",
        ),
    ] = None
    schedule_plan: typing_extensions.Annotated[
        typing.Optional[SchedulePlan],
        FieldMetadata(alias="schedulePlan"),
        pydantic.Field(
            alias="schedulePlan",
            description="This is the schedule plan for the campaign.\nCan only be updated if campaign is not in progress or has ended.",
        ),
    ] = None
    status: typing.Optional[UpdateCampaignDtoStatus] = pydantic.Field(default=None)
    """
    Set to 'cancelled' to stop the campaign ('ended' is a V1 alias). Scheduled
    calls are deleted; in-progress calls are allowed to finish.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(UpdateCampaignDto)
