# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class UpdateAssistantVersionMetadataDto(UncheckedBaseModel):
    version_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="versionName"),
        pydantic.Field(
            alias="versionName", description="Optional human-readable label for this version. Pass `null` to clear."
        ),
    ] = None
    version_description: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="versionDescription"),
        pydantic.Field(
            alias="versionDescription", description="Optional description for this version. Pass `null` to clear."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
