# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .update_eleven_labs_credential_dto_api_url import UpdateElevenLabsCredentialDtoApiUrl


class UpdateElevenLabsCredentialDto(UncheckedBaseModel):
    provider: typing.Optional[typing.Literal["11labs"]] = None
    api_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="apiKey"),
        pydantic.Field(alias="apiKey", description="This is not returned in the API."),
    ] = None
    api_url: typing_extensions.Annotated[
        typing.Optional[UpdateElevenLabsCredentialDtoApiUrl],
        FieldMetadata(alias="apiUrl"),
        pydantic.Field(
            alias="apiUrl",
            description="ElevenLabs-only API environment for this key: the global endpoint or the EU data residency endpoint. In EU deployments, new credentials must explicitly use the EU data residency endpoint; existing credentials may omit this field on update to retain their saved endpoint. Outside EU deployments, Vapi detects an omitted endpoint automatically and null on update clears and re-detects the endpoint.",
        ),
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    This is the name of credential. This is just for your reference.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
