# This file was auto-generated by Fern from our API Definition.

import typing

from .update_user_role_dto_role_zero import UpdateUserRoleDtoRoleZero

UpdateUserRoleDtoRole = typing.Union[UpdateUserRoleDtoRoleZero, str]
