# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .update_soniox_credential_dto_provider import UpdateSonioxCredentialDtoProvider


class UpdateSonioxCredentialDto(UncheckedBaseModel):
    provider: typing.Optional[UpdateSonioxCredentialDtoProvider] = None
    api_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="apiKey"),
        pydantic.Field(alias="apiKey", description="This is not returned in the API."),
    ] = None
    api_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="apiUrl"),
        pydantic.Field(
            alias="apiUrl",
            description="Custom Soniox WebSocket endpoint (e.g. EU server wss://stt-rt.eu.soniox.com/transcribe-websocket). Defaults to the region-appropriate endpoint when omitted.",
        ),
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    This is the name of credential. This is just for your reference.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
