# This file was auto-generated by Fern from our API Definition.

import typing

UpdateGoogleCalendarOAuth2AuthorizationCredentialDtoProvider = typing.Union[
    typing.Literal["google.calendar.oauth2-authorization"], typing.Any
]
