# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .vapi_pronunciation_dictionary_locator_provider import VapiPronunciationDictionaryLocatorProvider


class VapiPronunciationDictionaryLocator(UncheckedBaseModel):
    """
    Identifies a pronunciation dictionary and optional version used for voice synthesis.
    """

    pronunciation_dict_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="pronunciationDictId"),
        pydantic.Field(alias="pronunciationDictId", description="The pronunciation dictionary ID"),
    ]
    version_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="versionId"),
        pydantic.Field(alias="versionId", description="Version ID (only used by ElevenLabs, ignored for Cartesia)"),
    ] = None
    provider: typing.Optional[VapiPronunciationDictionaryLocatorProvider] = pydantic.Field(default=None)
    """
    Provider that hosts this pronunciation dictionary
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
