# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class VapiVoiceCloneDto(UncheckedBaseModel):
    name: str = pydantic.Field()
    """
    Display name for the cloned voice.
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional language (ISO-639 / BCP-47). When omitted, xAI infers it from the
    reference audio.
    """

    files: typing.List[str] = pydantic.Field()
    """
    Reference audio to clone the voice from (up to 120 seconds). Supported formats: MP3, WAV, OGG/Opus, WebM, AAC, M4A, FLAC, WMA.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
