# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .open_ai_message import OpenAiMessage
from .workflow_custom_model_metadata_send_mode import WorkflowCustomModelMetadataSendMode


class WorkflowCustomModel(UncheckedBaseModel):
    """
    Workflow model configuration for a custom language model endpoint, including URL, headers, metadata delivery, timeout, model, temperature, and maximum output tokens.
    """

    messages: typing.Optional[typing.List[OpenAiMessage]] = pydantic.Field(default=None)
    """
    These are the messages used to customize the prompt used for structured output extraction.
    
    When provided, these messages replace the default prompts. Message contents support LiquidJS templating with the following variables:
    - `{{transcript}}` or `{{messages}}` to reference the conversation (one is required)
    - `{{structuredOutput.name}}`, `{{structuredOutput.description}}`, or `{{structuredOutput.schema}}` to reference the structured output definition (one is required)
    - `{{systemPrompt}}`, `{{callEndedReason}}`, `{{duration}}`, `{{startedAt}}`, `{{endedAt}}`, and any `assistantOverrides.variableValues`
    
    `{{messages}}` is the full message history including tool calls; `{{transcript}}` is the spoken text only, which uses significantly fewer tokens.
    
    If not provided, default system and user prompts are used.
    """

    metadata_send_mode: typing_extensions.Annotated[
        typing.Optional[WorkflowCustomModelMetadataSendMode],
        FieldMetadata(alias="metadataSendMode"),
        pydantic.Field(
            alias="metadataSendMode",
            description="This determines whether metadata is sent in requests to the custom provider.\n\n- `off` will not send any metadata. payload will look like `{ messages }`\n- `variable` will send `assistant.metadata` as a variable on the payload. payload will look like `{ messages, metadata }`\n- `destructured` will send `assistant.metadata` fields directly on the payload. payload will look like `{ messages, ...metadata }`\n\nFurther, `variable` and `destructured` will send `call`, `phoneNumber`, and `customer` objects in the payload.\n\nDefault is `variable`.",
        ),
    ] = None
    url: str = pydantic.Field()
    """
    These is the URL we'll use for the OpenAI client's `baseURL`. Ex. https://openrouter.ai/api/v1
    """

    headers: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    These are the headers we'll use for the OpenAI client's `headers`.
    """

    timeout_seconds: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="timeoutSeconds"),
        pydantic.Field(
            alias="timeoutSeconds",
            description="This sets the timeout for the connection to the custom provider without needing to stream any tokens back. Default is 20 seconds.",
        ),
    ] = None
    model: str = pydantic.Field()
    """
    This is the name of the model. Ex. cognitivecomputations/dolphin-mixtral-8x7b
    """

    temperature: typing.Optional[float] = pydantic.Field(default=None)
    """
    This is the temperature of the model.
    """

    max_tokens: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="maxTokens"),
        pydantic.Field(alias="maxTokens", description="This is the max tokens of the model."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
