# This file was auto-generated by Fern from our API Definition.

import typing

XaiVoiceLanguage = typing.Union[
    typing.Literal[
        "auto",
        "en",
        "ar-EG",
        "ar-SA",
        "ar-AE",
        "bn",
        "zh",
        "fr",
        "de",
        "hi",
        "id",
        "it",
        "ja",
        "ko",
        "pt-BR",
        "pt-PT",
        "ru",
        "es-MX",
        "es-ES",
        "tr",
        "vi",
    ],
    typing.Any,
]
