# This file was auto-generated by Fern from our API Definition.

import typing

XaiModelModel = typing.Union[
    typing.Literal[
        "grok-beta",
        "grok-2",
        "grok-3",
        "grok-4-fast-reasoning",
        "grok-4-fast-non-reasoning",
        "grok-4.20-0309-reasoning",
        "grok-4.20-0309-non-reasoning",
        "grok-4.3",
    ],
    typing.Any,
]
