# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_traffic_allocation_target_dto import CreateTrafficAllocationTargetDto
from ..types.traffic_allocation import TrafficAllocation
from ..types.traffic_allocation_latest_response_dto import TrafficAllocationLatestResponseDto
from ..types.traffic_allocation_paginated_response import TrafficAllocationPaginatedResponse
from .raw_client import AsyncRawTrafficAllocationsClient, RawTrafficAllocationsClient
from .types.create_traffic_allocation_dto_allocation_intent import CreateTrafficAllocationDtoAllocationIntent
from .types.traffic_allocation_controller_find_all_paginated_request_sort_order import (
    TrafficAllocationControllerFindAllPaginatedRequestSortOrder,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TrafficAllocationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTrafficAllocationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTrafficAllocationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTrafficAllocationsClient
        """
        return self._raw_client

    def traffic_allocation_controller_find_all_paginated(
        self,
        *,
        assistant_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort_order: typing.Optional[TrafficAllocationControllerFindAllPaginatedRequestSortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TrafficAllocationPaginatedResponse:
        """
        The append-only history of an assistant's allocations, newest first. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.

        Parameters
        ----------
        assistant_id : typing.Optional[str]
            Filter to allocations for this assistant.

        page : typing.Optional[int]
            The page number to return. Defaults to 1.

        limit : typing.Optional[int]
            The maximum number of items to return. Defaults to 100.

        sort_order : typing.Optional[TrafficAllocationControllerFindAllPaginatedRequestSortOrder]
            The sort order for pagination. Defaults to 'DESC'.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrafficAllocationPaginatedResponse


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.traffic_allocations.traffic_allocation_controller_find_all_paginated()
        """
        _response = self._raw_client.traffic_allocation_controller_find_all_paginated(
            assistant_id=assistant_id, page=page, limit=limit, sort_order=sort_order, request_options=request_options
        )
        return _response.data

    def traffic_allocation_controller_create(
        self,
        *,
        assistant_id: str,
        allocation_intent: typing.Optional[CreateTrafficAllocationDtoAllocationIntent] = OMIT,
        targets: typing.Optional[typing.Sequence[CreateTrafficAllocationTargetDto]] = OMIT,
        expected_current_allocation_id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TrafficAllocation:
        """
        Creates a new traffic allocation for an assistant, replacing the one currently in effect. To start or adjust a split, send targets naming published versions (such as "v7") with percentages totaling 100; allocationIntent is inferred as 'explicit'. To stop splitting and send every call to the newest published version, send allocationIntent 'follow-latest' with no targets field; stopping always names its intent, so a dropped targets field can never end a split by accident. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.

        Parameters
        ----------
        assistant_id : str
            The assistant whose calls this allocation splits.

        allocation_intent : typing.Optional[CreateTrafficAllocationDtoAllocationIntent]
            'explicit' splits calls across targets, and is inferred when targets is sent. 'follow-latest' sends every call to the newest published version and is how you stop splitting; it must be sent explicitly.

        targets : typing.Optional[typing.Sequence[CreateTrafficAllocationTargetDto]]
            The versions to split calls across. Omit to stop splitting (with allocationIntent 'follow-latest'). Order in this array is the selection order (position).

        expected_current_allocation_id : typing.Optional[str]
            Optional concurrency guard. Omit it and the write applies unconditionally (last write wins, matching every other Vapi update surface). Provide the id of the allocation you last read and the write applies only while that allocation is still governing; any mismatch is a 409 carrying the actual current id.

        description : typing.Optional[str]
            An optional note explaining why you made this change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrafficAllocation


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.traffic_allocations.traffic_allocation_controller_create(
            assistant_id="assistantId",
        )
        """
        _response = self._raw_client.traffic_allocation_controller_create(
            assistant_id=assistant_id,
            allocation_intent=allocation_intent,
            targets=targets,
            expected_current_allocation_id=expected_current_allocation_id,
            description=description,
            request_options=request_options,
        )
        return _response.data

    def traffic_allocation_controller_latest_get(
        self, *, assistant_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TrafficAllocationLatestResponseDto:
        """
        The allocation currently in effect for the assistant, with its targets. The response carries no allocation field when traffic splitting has never been configured. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.

        Parameters
        ----------
        assistant_id : str
            The assistant whose latest allocation to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrafficAllocationLatestResponseDto


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.traffic_allocations.traffic_allocation_controller_latest_get(
            assistant_id="assistantId",
        )
        """
        _response = self._raw_client.traffic_allocation_controller_latest_get(
            assistant_id=assistant_id, request_options=request_options
        )
        return _response.data

    def traffic_allocation_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TrafficAllocation:
        """
        Returns a single allocation by id, including its targets and actor attribution. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrafficAllocation


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.traffic_allocations.traffic_allocation_controller_find_one(
            id="id",
        )
        """
        _response = self._raw_client.traffic_allocation_controller_find_one(id, request_options=request_options)
        return _response.data


class AsyncTrafficAllocationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTrafficAllocationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTrafficAllocationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTrafficAllocationsClient
        """
        return self._raw_client

    async def traffic_allocation_controller_find_all_paginated(
        self,
        *,
        assistant_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort_order: typing.Optional[TrafficAllocationControllerFindAllPaginatedRequestSortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TrafficAllocationPaginatedResponse:
        """
        The append-only history of an assistant's allocations, newest first. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.

        Parameters
        ----------
        assistant_id : typing.Optional[str]
            Filter to allocations for this assistant.

        page : typing.Optional[int]
            The page number to return. Defaults to 1.

        limit : typing.Optional[int]
            The maximum number of items to return. Defaults to 100.

        sort_order : typing.Optional[TrafficAllocationControllerFindAllPaginatedRequestSortOrder]
            The sort order for pagination. Defaults to 'DESC'.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrafficAllocationPaginatedResponse


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.traffic_allocations.traffic_allocation_controller_find_all_paginated()


        asyncio.run(main())
        """
        _response = await self._raw_client.traffic_allocation_controller_find_all_paginated(
            assistant_id=assistant_id, page=page, limit=limit, sort_order=sort_order, request_options=request_options
        )
        return _response.data

    async def traffic_allocation_controller_create(
        self,
        *,
        assistant_id: str,
        allocation_intent: typing.Optional[CreateTrafficAllocationDtoAllocationIntent] = OMIT,
        targets: typing.Optional[typing.Sequence[CreateTrafficAllocationTargetDto]] = OMIT,
        expected_current_allocation_id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TrafficAllocation:
        """
        Creates a new traffic allocation for an assistant, replacing the one currently in effect. To start or adjust a split, send targets naming published versions (such as "v7") with percentages totaling 100; allocationIntent is inferred as 'explicit'. To stop splitting and send every call to the newest published version, send allocationIntent 'follow-latest' with no targets field; stopping always names its intent, so a dropped targets field can never end a split by accident. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.

        Parameters
        ----------
        assistant_id : str
            The assistant whose calls this allocation splits.

        allocation_intent : typing.Optional[CreateTrafficAllocationDtoAllocationIntent]
            'explicit' splits calls across targets, and is inferred when targets is sent. 'follow-latest' sends every call to the newest published version and is how you stop splitting; it must be sent explicitly.

        targets : typing.Optional[typing.Sequence[CreateTrafficAllocationTargetDto]]
            The versions to split calls across. Omit to stop splitting (with allocationIntent 'follow-latest'). Order in this array is the selection order (position).

        expected_current_allocation_id : typing.Optional[str]
            Optional concurrency guard. Omit it and the write applies unconditionally (last write wins, matching every other Vapi update surface). Provide the id of the allocation you last read and the write applies only while that allocation is still governing; any mismatch is a 409 carrying the actual current id.

        description : typing.Optional[str]
            An optional note explaining why you made this change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrafficAllocation


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.traffic_allocations.traffic_allocation_controller_create(
                assistant_id="assistantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.traffic_allocation_controller_create(
            assistant_id=assistant_id,
            allocation_intent=allocation_intent,
            targets=targets,
            expected_current_allocation_id=expected_current_allocation_id,
            description=description,
            request_options=request_options,
        )
        return _response.data

    async def traffic_allocation_controller_latest_get(
        self, *, assistant_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TrafficAllocationLatestResponseDto:
        """
        The allocation currently in effect for the assistant, with its targets. The response carries no allocation field when traffic splitting has never been configured. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.

        Parameters
        ----------
        assistant_id : str
            The assistant whose latest allocation to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrafficAllocationLatestResponseDto


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.traffic_allocations.traffic_allocation_controller_latest_get(
                assistant_id="assistantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.traffic_allocation_controller_latest_get(
            assistant_id=assistant_id, request_options=request_options
        )
        return _response.data

    async def traffic_allocation_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TrafficAllocation:
        """
        Returns a single allocation by id, including its targets and actor attribution. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrafficAllocation


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.traffic_allocations.traffic_allocation_controller_find_one(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.traffic_allocation_controller_find_one(id, request_options=request_options)
        return _response.data
