# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.board import Board
from ..types.board_layout import BoardLayout
from ..types.board_paginated_response import BoardPaginatedResponse
from ..types.insight_time_range_with_step import InsightTimeRangeWithStep
from .raw_client import AsyncRawBoardClient, RawBoardClient
from .types.board_controller_find_all_request_sort_by import BoardControllerFindAllRequestSortBy
from .types.board_controller_find_all_request_sort_order import BoardControllerFindAllRequestSortOrder
from .types.create_board_dto_items_item import CreateBoardDtoItemsItem
from .types.update_board_dto_items_item import UpdateBoardDtoItemsItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BoardClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBoardClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBoardClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBoardClient
        """
        return self._raw_client

    def board_controller_find_all(
        self,
        *,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[BoardControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[BoardControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BoardPaginatedResponse:
        """
        Parameters
        ----------
        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[BoardControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[BoardControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BoardPaginatedResponse


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.board.board_controller_find_all()
        """
        _response = self._raw_client.board_controller_find_all(
            page=page,
            sort_order=sort_order,
            sort_by=sort_by,
            limit=limit,
            created_at_gt=created_at_gt,
            created_at_lt=created_at_lt,
            created_at_ge=created_at_ge,
            created_at_le=created_at_le,
            updated_at_gt=updated_at_gt,
            updated_at_lt=updated_at_lt,
            updated_at_ge=updated_at_ge,
            updated_at_le=updated_at_le,
            request_options=request_options,
        )
        return _response.data

    def board_controller_create(
        self,
        *,
        name: str,
        layout: BoardLayout,
        items: typing.Optional[typing.Sequence[CreateBoardDtoItemsItem]] = OMIT,
        time_range_override: typing.Optional[InsightTimeRangeWithStep] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Board:
        """
        Parameters
        ----------
        name : str
            This is the name of the Board.

        layout : BoardLayout
            This is the layout of the Board.

        items : typing.Optional[typing.Sequence[CreateBoardDtoItemsItem]]
            This is the contents of the Board, which is an array of objects defining the type, contents, and position of the widgets on the Board.

        time_range_override : typing.Optional[InsightTimeRangeWithStep]
            This is the timerange override for the board.
            By default, individual insights have their own timerange.
            This is a global override for the board which will be passed to all insights on the board.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        from vapi import BoardLayout, Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.board.board_controller_create(
            name="name",
            layout=BoardLayout(
                columns=1.1,
            ),
        )
        """
        _response = self._raw_client.board_controller_create(
            name=name,
            layout=layout,
            items=items,
            time_range_override=time_range_override,
            request_options=request_options,
        )
        return _response.data

    def board_controller_metrics_overview_ensure(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Board:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.board.board_controller_metrics_overview_ensure()
        """
        _response = self._raw_client.board_controller_metrics_overview_ensure(request_options=request_options)
        return _response.data

    def board_controller_find_one(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Board:
        """
        Parameters
        ----------
        id : str
            The unique identifier for the resource.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.board.board_controller_find_one(
            id="id",
        )
        """
        _response = self._raw_client.board_controller_find_one(id, request_options=request_options)
        return _response.data

    def board_controller_remove(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Board:
        """
        Parameters
        ----------
        id : str
            The unique identifier for the resource.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.board.board_controller_remove(
            id="id",
        )
        """
        _response = self._raw_client.board_controller_remove(id, request_options=request_options)
        return _response.data

    def board_controller_update(
        self,
        id: str,
        *,
        items: typing.Optional[typing.Sequence[UpdateBoardDtoItemsItem]] = OMIT,
        name: typing.Optional[str] = OMIT,
        layout: typing.Optional[BoardLayout] = OMIT,
        time_range_override: typing.Optional[InsightTimeRangeWithStep] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Board:
        """
        Parameters
        ----------
        id : str
            The unique identifier for the resource.

        items : typing.Optional[typing.Sequence[UpdateBoardDtoItemsItem]]
            This is the contents of the Board, which is an array of objects defining the type, contents, and position of the widgets on the Board.

        name : typing.Optional[str]
            This is the name of the Board.

        layout : typing.Optional[BoardLayout]
            This is the layout of the Board.

        time_range_override : typing.Optional[InsightTimeRangeWithStep]
            This is the timerange override for the board.
            By default, individual insights have their own timerange.
            This is a global override for the board which will be passed to all insights on the board.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.board.board_controller_update(
            id="id",
        )
        """
        _response = self._raw_client.board_controller_update(
            id,
            items=items,
            name=name,
            layout=layout,
            time_range_override=time_range_override,
            request_options=request_options,
        )
        return _response.data


class AsyncBoardClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBoardClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBoardClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBoardClient
        """
        return self._raw_client

    async def board_controller_find_all(
        self,
        *,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[BoardControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[BoardControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BoardPaginatedResponse:
        """
        Parameters
        ----------
        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[BoardControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[BoardControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BoardPaginatedResponse


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.board.board_controller_find_all()


        asyncio.run(main())
        """
        _response = await self._raw_client.board_controller_find_all(
            page=page,
            sort_order=sort_order,
            sort_by=sort_by,
            limit=limit,
            created_at_gt=created_at_gt,
            created_at_lt=created_at_lt,
            created_at_ge=created_at_ge,
            created_at_le=created_at_le,
            updated_at_gt=updated_at_gt,
            updated_at_lt=updated_at_lt,
            updated_at_ge=updated_at_ge,
            updated_at_le=updated_at_le,
            request_options=request_options,
        )
        return _response.data

    async def board_controller_create(
        self,
        *,
        name: str,
        layout: BoardLayout,
        items: typing.Optional[typing.Sequence[CreateBoardDtoItemsItem]] = OMIT,
        time_range_override: typing.Optional[InsightTimeRangeWithStep] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Board:
        """
        Parameters
        ----------
        name : str
            This is the name of the Board.

        layout : BoardLayout
            This is the layout of the Board.

        items : typing.Optional[typing.Sequence[CreateBoardDtoItemsItem]]
            This is the contents of the Board, which is an array of objects defining the type, contents, and position of the widgets on the Board.

        time_range_override : typing.Optional[InsightTimeRangeWithStep]
            This is the timerange override for the board.
            By default, individual insights have their own timerange.
            This is a global override for the board which will be passed to all insights on the board.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi, BoardLayout

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.board.board_controller_create(
                name="name",
                layout=BoardLayout(
                    columns=1.1,
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.board_controller_create(
            name=name,
            layout=layout,
            items=items,
            time_range_override=time_range_override,
            request_options=request_options,
        )
        return _response.data

    async def board_controller_metrics_overview_ensure(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Board:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.board.board_controller_metrics_overview_ensure()


        asyncio.run(main())
        """
        _response = await self._raw_client.board_controller_metrics_overview_ensure(request_options=request_options)
        return _response.data

    async def board_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Board:
        """
        Parameters
        ----------
        id : str
            The unique identifier for the resource.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.board.board_controller_find_one(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.board_controller_find_one(id, request_options=request_options)
        return _response.data

    async def board_controller_remove(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Board:
        """
        Parameters
        ----------
        id : str
            The unique identifier for the resource.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.board.board_controller_remove(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.board_controller_remove(id, request_options=request_options)
        return _response.data

    async def board_controller_update(
        self,
        id: str,
        *,
        items: typing.Optional[typing.Sequence[UpdateBoardDtoItemsItem]] = OMIT,
        name: typing.Optional[str] = OMIT,
        layout: typing.Optional[BoardLayout] = OMIT,
        time_range_override: typing.Optional[InsightTimeRangeWithStep] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Board:
        """
        Parameters
        ----------
        id : str
            The unique identifier for the resource.

        items : typing.Optional[typing.Sequence[UpdateBoardDtoItemsItem]]
            This is the contents of the Board, which is an array of objects defining the type, contents, and position of the widgets on the Board.

        name : typing.Optional[str]
            This is the name of the Board.

        layout : typing.Optional[BoardLayout]
            This is the layout of the Board.

        time_range_override : typing.Optional[InsightTimeRangeWithStep]
            This is the timerange override for the board.
            By default, individual insights have their own timerange.
            This is a global override for the board which will be passed to all insights on the board.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Board


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.board.board_controller_update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.board_controller_update(
            id,
            items=items,
            name=name,
            layout=layout,
            time_range_override=time_range_override,
            request_options=request_options,
        )
        return _response.data
