# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from ..types.generate_scenarios_response import GenerateScenariosResponse
from ..types.simulation import Simulation
from ..types.simulation_concurrency_response import SimulationConcurrencyResponse
from .types.simulation_controller_find_all_request_sort_by import SimulationControllerFindAllRequestSortBy
from .types.simulation_controller_find_all_request_sort_order import SimulationControllerFindAllRequestSortOrder
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSimulationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def simulation_generate_controller_generate(
        self,
        *,
        assistant_id: typing.Optional[str] = OMIT,
        squad_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GenerateScenariosResponse]:
        """
        Generates scenarios for an assistant or squad by analyzing its configuration with AI.

        Parameters
        ----------
        assistant_id : typing.Optional[str]
            ID of the assistant to generate scenarios for

        squad_id : typing.Optional[str]
            ID of the squad to generate scenarios for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GenerateScenariosResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            "eval/simulation/scenario/generate",
            method="POST",
            json={
                "assistantId": assistant_id,
                "squadId": squad_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GenerateScenariosResponse,
                    construct_type(
                        type_=GenerateScenariosResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_controller_find_all(
        self,
        *,
        id_any: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        standalone_only: typing.Optional[bool] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[SimulationControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[SimulationControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[Simulation]]:
        """
        Returns the simulations for the authenticated organization.

        Parameters
        ----------
        id_any : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Return only simulations matching the provided ids

        standalone_only : typing.Optional[bool]
            Only include simulations that are not part of a suite

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[SimulationControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[SimulationControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[Simulation]]

        """
        _response = self._client_wrapper.httpx_client.request(
            "eval/simulation",
            method="GET",
            params={
                "idAny": id_any,
                "standaloneOnly": standalone_only,
                "page": page,
                "sortOrder": sort_order,
                "sortBy": sort_by,
                "limit": limit,
                "createdAtGt": serialize_datetime(created_at_gt) if created_at_gt is not None else None,
                "createdAtLt": serialize_datetime(created_at_lt) if created_at_lt is not None else None,
                "createdAtGe": serialize_datetime(created_at_ge) if created_at_ge is not None else None,
                "createdAtLe": serialize_datetime(created_at_le) if created_at_le is not None else None,
                "updatedAtGt": serialize_datetime(updated_at_gt) if updated_at_gt is not None else None,
                "updatedAtLt": serialize_datetime(updated_at_lt) if updated_at_lt is not None else None,
                "updatedAtGe": serialize_datetime(updated_at_ge) if updated_at_ge is not None else None,
                "updatedAtLe": serialize_datetime(updated_at_le) if updated_at_le is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[Simulation],
                    construct_type(
                        type_=typing.List[Simulation],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_controller_create(
        self,
        *,
        scenario_id: str,
        personality_id: str,
        name: typing.Optional[str] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Simulation]:
        """
        Creates a simulation by pairing a scenario with a personality.

        Parameters
        ----------
        scenario_id : str
            The ID of the scenario to run.

        personality_id : str
            The ID of the personality the AI tester uses.

        name : typing.Optional[str]
            Optional display name for the simulation.

        path : typing.Optional[str]
            Optional folder path for organizing simulations.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Maps to GitOps resource folder structure.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Simulation]

        """
        _response = self._client_wrapper.httpx_client.request(
            "eval/simulation",
            method="POST",
            json={
                "name": name,
                "scenarioId": scenario_id,
                "personalityId": personality_id,
                "path": path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Simulation,
                    construct_type(
                        type_=Simulation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Simulation]:
        """
        Returns the specified simulation.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Simulation]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Simulation,
                    construct_type(
                        type_=Simulation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_controller_remove(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Simulation]:
        """
        Deletes the specified simulation.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Simulation]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Simulation,
                    construct_type(
                        type_=Simulation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_controller_update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        scenario_id: typing.Optional[str] = OMIT,
        personality_id: typing.Optional[str] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Simulation]:
        """
        Updates the specified simulation.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation.

        name : typing.Optional[str]
            This is an optional friendly name for the simulation.

        scenario_id : typing.Optional[str]
            This is the ID of the scenario to use for this simulation.

        personality_id : typing.Optional[str]
            This is the ID of the personality to use for this simulation.

        path : typing.Optional[str]
            Optional folder path for organizing simulations.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Set to null to remove from folder.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Simulation]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "name": name,
                "scenarioId": scenario_id,
                "personalityId": personality_id,
                "path": path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Simulation,
                    construct_type(
                        type_=Simulation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def simulation_controller_get_concurrency(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SimulationConcurrencyResponse]:
        """
        Returns the organization's simulation concurrency limit, the number of active simulations, and how many more can start.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SimulationConcurrencyResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            "eval/simulation/concurrency",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationConcurrencyResponse,
                    construct_type(
                        type_=SimulationConcurrencyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSimulationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def simulation_generate_controller_generate(
        self,
        *,
        assistant_id: typing.Optional[str] = OMIT,
        squad_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GenerateScenariosResponse]:
        """
        Generates scenarios for an assistant or squad by analyzing its configuration with AI.

        Parameters
        ----------
        assistant_id : typing.Optional[str]
            ID of the assistant to generate scenarios for

        squad_id : typing.Optional[str]
            ID of the squad to generate scenarios for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GenerateScenariosResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "eval/simulation/scenario/generate",
            method="POST",
            json={
                "assistantId": assistant_id,
                "squadId": squad_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GenerateScenariosResponse,
                    construct_type(
                        type_=GenerateScenariosResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_controller_find_all(
        self,
        *,
        id_any: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        standalone_only: typing.Optional[bool] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[SimulationControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[SimulationControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[Simulation]]:
        """
        Returns the simulations for the authenticated organization.

        Parameters
        ----------
        id_any : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Return only simulations matching the provided ids

        standalone_only : typing.Optional[bool]
            Only include simulations that are not part of a suite

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[SimulationControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[SimulationControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[Simulation]]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "eval/simulation",
            method="GET",
            params={
                "idAny": id_any,
                "standaloneOnly": standalone_only,
                "page": page,
                "sortOrder": sort_order,
                "sortBy": sort_by,
                "limit": limit,
                "createdAtGt": serialize_datetime(created_at_gt) if created_at_gt is not None else None,
                "createdAtLt": serialize_datetime(created_at_lt) if created_at_lt is not None else None,
                "createdAtGe": serialize_datetime(created_at_ge) if created_at_ge is not None else None,
                "createdAtLe": serialize_datetime(created_at_le) if created_at_le is not None else None,
                "updatedAtGt": serialize_datetime(updated_at_gt) if updated_at_gt is not None else None,
                "updatedAtLt": serialize_datetime(updated_at_lt) if updated_at_lt is not None else None,
                "updatedAtGe": serialize_datetime(updated_at_ge) if updated_at_ge is not None else None,
                "updatedAtLe": serialize_datetime(updated_at_le) if updated_at_le is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[Simulation],
                    construct_type(
                        type_=typing.List[Simulation],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_controller_create(
        self,
        *,
        scenario_id: str,
        personality_id: str,
        name: typing.Optional[str] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Simulation]:
        """
        Creates a simulation by pairing a scenario with a personality.

        Parameters
        ----------
        scenario_id : str
            The ID of the scenario to run.

        personality_id : str
            The ID of the personality the AI tester uses.

        name : typing.Optional[str]
            Optional display name for the simulation.

        path : typing.Optional[str]
            Optional folder path for organizing simulations.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Maps to GitOps resource folder structure.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Simulation]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "eval/simulation",
            method="POST",
            json={
                "name": name,
                "scenarioId": scenario_id,
                "personalityId": personality_id,
                "path": path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Simulation,
                    construct_type(
                        type_=Simulation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Simulation]:
        """
        Returns the specified simulation.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Simulation]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Simulation,
                    construct_type(
                        type_=Simulation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_controller_remove(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Simulation]:
        """
        Deletes the specified simulation.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Simulation]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Simulation,
                    construct_type(
                        type_=Simulation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_controller_update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        scenario_id: typing.Optional[str] = OMIT,
        personality_id: typing.Optional[str] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Simulation]:
        """
        Updates the specified simulation.

        Parameters
        ----------
        id : str
            The unique identifier of the simulation.

        name : typing.Optional[str]
            This is an optional friendly name for the simulation.

        scenario_id : typing.Optional[str]
            This is the ID of the scenario to use for this simulation.

        personality_id : typing.Optional[str]
            This is the ID of the personality to use for this simulation.

        path : typing.Optional[str]
            Optional folder path for organizing simulations.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Set to null to remove from folder.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Simulation]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "name": name,
                "scenarioId": scenario_id,
                "personalityId": personality_id,
                "path": path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Simulation,
                    construct_type(
                        type_=Simulation,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def simulation_controller_get_concurrency(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SimulationConcurrencyResponse]:
        """
        Returns the organization's simulation concurrency limit, the number of active simulations, and how many more can start.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SimulationConcurrencyResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "eval/simulation/concurrency",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SimulationConcurrencyResponse,
                    construct_type(
                        type_=SimulationConcurrencyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
