# This file was auto-generated by Fern from our API Definition.

import typing

ProviderResourceControllerGetProviderResourcesPaginatedRequestSortBy = typing.Union[
    typing.Literal["createdAt", "duration", "cost"], typing.Any
]
