# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.assistant_overrides import AssistantOverrides
from ..types.create_scenario_dto_hooks_item import CreateScenarioDtoHooksItem
from ..types.evaluation_plan_item import EvaluationPlanItem
from ..types.scenario import Scenario
from ..types.scenario_tool_mock import ScenarioToolMock
from .raw_client import AsyncRawSimulationScenariosClient, RawSimulationScenariosClient
from .types.scenario_controller_find_all_request_sort_by import ScenarioControllerFindAllRequestSortBy
from .types.scenario_controller_find_all_request_sort_order import ScenarioControllerFindAllRequestSortOrder
from .types.update_scenario_dto_hooks_item import UpdateScenarioDtoHooksItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SimulationScenariosClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSimulationScenariosClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSimulationScenariosClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSimulationScenariosClient
        """
        return self._raw_client

    def scenario_controller_find_all(
        self,
        *,
        id_any: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        name: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[ScenarioControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[ScenarioControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[Scenario]:
        """
        Returns the scenarios for the authenticated organization.

        Parameters
        ----------
        id_any : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Return only scenarios matching the provided ids

        name : typing.Optional[str]
            Search by scenario name

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[ScenarioControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[ScenarioControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Scenario]


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.simulation_scenarios.scenario_controller_find_all()
        """
        _response = self._raw_client.scenario_controller_find_all(
            id_any=id_any,
            name=name,
            page=page,
            sort_order=sort_order,
            sort_by=sort_by,
            limit=limit,
            created_at_gt=created_at_gt,
            created_at_lt=created_at_lt,
            created_at_ge=created_at_ge,
            created_at_le=created_at_le,
            updated_at_gt=updated_at_gt,
            updated_at_lt=updated_at_lt,
            updated_at_ge=updated_at_ge,
            updated_at_le=updated_at_le,
            request_options=request_options,
        )
        return _response.data

    def scenario_controller_create(
        self,
        *,
        name: str,
        instructions: str,
        evaluations: typing.Sequence[EvaluationPlanItem],
        hooks: typing.Optional[typing.Sequence[CreateScenarioDtoHooksItem]] = OMIT,
        target_overrides: typing.Optional[AssistantOverrides] = OMIT,
        tool_mocks: typing.Optional[typing.Sequence[ScenarioToolMock]] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Scenario:
        """
        Creates a scenario, the AI tester's intent plus the success criteria that score a run.

        Parameters
        ----------
        name : str
            The display name of the scenario, for example `Book an appointment`.

        instructions : str
            What the AI tester should try to accomplish in the conversation. Write it as the AI tester's goal, for example `Book an appointment for next week and confirm the time.`

        evaluations : typing.Sequence[EvaluationPlanItem]
            The checks that decide whether a run passes. Each evaluation compares a structured output against an expected value. At least one evaluation is required to run.

        hooks : typing.Optional[typing.Sequence[CreateScenarioDtoHooksItem]]
            Hooks to run on simulation lifecycle events

        target_overrides : typing.Optional[AssistantOverrides]
            Overrides to inject into the simulated target assistant or squad

        tool_mocks : typing.Optional[typing.Sequence[ScenarioToolMock]]
            Mock results for the assistant or squad's tools during the simulation, so the run stays deterministic without calling real services.

        path : typing.Optional[str]
            Optional folder path for organizing scenarios.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Maps to GitOps resource folder structure.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Scenario


        Examples
        --------
        from vapi import EvaluationPlanItem, Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.simulation_scenarios.scenario_controller_create(
            name="Health Enrollment - Eligible Path",
            instructions="You are calling to enroll in the Twin Health program. Confirm your identity when asked.",
            evaluations=[
                EvaluationPlanItem(
                    comparator="=",
                    value=1.1,
                )
            ],
        )
        """
        _response = self._raw_client.scenario_controller_create(
            name=name,
            instructions=instructions,
            evaluations=evaluations,
            hooks=hooks,
            target_overrides=target_overrides,
            tool_mocks=tool_mocks,
            path=path,
            request_options=request_options,
        )
        return _response.data

    def scenario_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Scenario:
        """
        Returns the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Scenario


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.simulation_scenarios.scenario_controller_find_one(
            id="id",
        )
        """
        _response = self._raw_client.scenario_controller_find_one(id, request_options=request_options)
        return _response.data

    def scenario_controller_remove(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Scenario:
        """
        Deletes the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Scenario


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.simulation_scenarios.scenario_controller_remove(
            id="id",
        )
        """
        _response = self._raw_client.scenario_controller_remove(id, request_options=request_options)
        return _response.data

    def scenario_controller_update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        evaluations: typing.Optional[typing.Sequence[EvaluationPlanItem]] = OMIT,
        hooks: typing.Optional[typing.Sequence[UpdateScenarioDtoHooksItem]] = OMIT,
        target_overrides: typing.Optional[AssistantOverrides] = OMIT,
        tool_mocks: typing.Optional[typing.Sequence[ScenarioToolMock]] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Scenario:
        """
        Updates the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        name : typing.Optional[str]
            This is the name of the scenario.

        instructions : typing.Optional[str]
            This is the script/instructions for the tester to follow during the simulation.

        evaluations : typing.Optional[typing.Sequence[EvaluationPlanItem]]
            This is the structured output-based evaluation plan for the simulation.
            Each item defines a structured output to extract and evaluate against an expected value.

        hooks : typing.Optional[typing.Sequence[UpdateScenarioDtoHooksItem]]
            Hooks to run on simulation lifecycle events

        target_overrides : typing.Optional[AssistantOverrides]
            Overrides to inject into the simulated target assistant or squad

        tool_mocks : typing.Optional[typing.Sequence[ScenarioToolMock]]

        path : typing.Optional[str]
            Optional folder path for organizing scenarios.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Set to null to remove from folder.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Scenario


        Examples
        --------
        from vapi import Vapi

        client = Vapi(
            token="YOUR_TOKEN",
        )
        client.simulation_scenarios.scenario_controller_update(
            id="id",
        )
        """
        _response = self._raw_client.scenario_controller_update(
            id,
            name=name,
            instructions=instructions,
            evaluations=evaluations,
            hooks=hooks,
            target_overrides=target_overrides,
            tool_mocks=tool_mocks,
            path=path,
            request_options=request_options,
        )
        return _response.data


class AsyncSimulationScenariosClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSimulationScenariosClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSimulationScenariosClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSimulationScenariosClient
        """
        return self._raw_client

    async def scenario_controller_find_all(
        self,
        *,
        id_any: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        name: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[ScenarioControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[ScenarioControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[Scenario]:
        """
        Returns the scenarios for the authenticated organization.

        Parameters
        ----------
        id_any : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Return only scenarios matching the provided ids

        name : typing.Optional[str]
            Search by scenario name

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[ScenarioControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[ScenarioControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Scenario]


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.simulation_scenarios.scenario_controller_find_all()


        asyncio.run(main())
        """
        _response = await self._raw_client.scenario_controller_find_all(
            id_any=id_any,
            name=name,
            page=page,
            sort_order=sort_order,
            sort_by=sort_by,
            limit=limit,
            created_at_gt=created_at_gt,
            created_at_lt=created_at_lt,
            created_at_ge=created_at_ge,
            created_at_le=created_at_le,
            updated_at_gt=updated_at_gt,
            updated_at_lt=updated_at_lt,
            updated_at_ge=updated_at_ge,
            updated_at_le=updated_at_le,
            request_options=request_options,
        )
        return _response.data

    async def scenario_controller_create(
        self,
        *,
        name: str,
        instructions: str,
        evaluations: typing.Sequence[EvaluationPlanItem],
        hooks: typing.Optional[typing.Sequence[CreateScenarioDtoHooksItem]] = OMIT,
        target_overrides: typing.Optional[AssistantOverrides] = OMIT,
        tool_mocks: typing.Optional[typing.Sequence[ScenarioToolMock]] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Scenario:
        """
        Creates a scenario, the AI tester's intent plus the success criteria that score a run.

        Parameters
        ----------
        name : str
            The display name of the scenario, for example `Book an appointment`.

        instructions : str
            What the AI tester should try to accomplish in the conversation. Write it as the AI tester's goal, for example `Book an appointment for next week and confirm the time.`

        evaluations : typing.Sequence[EvaluationPlanItem]
            The checks that decide whether a run passes. Each evaluation compares a structured output against an expected value. At least one evaluation is required to run.

        hooks : typing.Optional[typing.Sequence[CreateScenarioDtoHooksItem]]
            Hooks to run on simulation lifecycle events

        target_overrides : typing.Optional[AssistantOverrides]
            Overrides to inject into the simulated target assistant or squad

        tool_mocks : typing.Optional[typing.Sequence[ScenarioToolMock]]
            Mock results for the assistant or squad's tools during the simulation, so the run stays deterministic without calling real services.

        path : typing.Optional[str]
            Optional folder path for organizing scenarios.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Maps to GitOps resource folder structure.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Scenario


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi, EvaluationPlanItem

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.simulation_scenarios.scenario_controller_create(
                name="Health Enrollment - Eligible Path",
                instructions="You are calling to enroll in the Twin Health program. Confirm your identity when asked.",
                evaluations=[
                    EvaluationPlanItem(
                        comparator="=",
                        value=1.1,
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.scenario_controller_create(
            name=name,
            instructions=instructions,
            evaluations=evaluations,
            hooks=hooks,
            target_overrides=target_overrides,
            tool_mocks=tool_mocks,
            path=path,
            request_options=request_options,
        )
        return _response.data

    async def scenario_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Scenario:
        """
        Returns the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Scenario


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.simulation_scenarios.scenario_controller_find_one(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.scenario_controller_find_one(id, request_options=request_options)
        return _response.data

    async def scenario_controller_remove(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Scenario:
        """
        Deletes the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Scenario


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.simulation_scenarios.scenario_controller_remove(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.scenario_controller_remove(id, request_options=request_options)
        return _response.data

    async def scenario_controller_update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        evaluations: typing.Optional[typing.Sequence[EvaluationPlanItem]] = OMIT,
        hooks: typing.Optional[typing.Sequence[UpdateScenarioDtoHooksItem]] = OMIT,
        target_overrides: typing.Optional[AssistantOverrides] = OMIT,
        tool_mocks: typing.Optional[typing.Sequence[ScenarioToolMock]] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Scenario:
        """
        Updates the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        name : typing.Optional[str]
            This is the name of the scenario.

        instructions : typing.Optional[str]
            This is the script/instructions for the tester to follow during the simulation.

        evaluations : typing.Optional[typing.Sequence[EvaluationPlanItem]]
            This is the structured output-based evaluation plan for the simulation.
            Each item defines a structured output to extract and evaluate against an expected value.

        hooks : typing.Optional[typing.Sequence[UpdateScenarioDtoHooksItem]]
            Hooks to run on simulation lifecycle events

        target_overrides : typing.Optional[AssistantOverrides]
            Overrides to inject into the simulated target assistant or squad

        tool_mocks : typing.Optional[typing.Sequence[ScenarioToolMock]]

        path : typing.Optional[str]
            Optional folder path for organizing scenarios.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Set to null to remove from folder.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Scenario


        Examples
        --------
        import asyncio

        from vapi import AsyncVapi

        client = AsyncVapi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.simulation_scenarios.scenario_controller_update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.scenario_controller_update(
            id,
            name=name,
            instructions=instructions,
            evaluations=evaluations,
            hooks=hooks,
            target_overrides=target_overrides,
            tool_mocks=tool_mocks,
            path=path,
            request_options=request_options,
        )
        return _response.data
