# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from ..types.assistant_overrides import AssistantOverrides
from ..types.create_scenario_dto_hooks_item import CreateScenarioDtoHooksItem
from ..types.evaluation_plan_item import EvaluationPlanItem
from ..types.scenario import Scenario
from ..types.scenario_tool_mock import ScenarioToolMock
from .types.scenario_controller_find_all_request_sort_by import ScenarioControllerFindAllRequestSortBy
from .types.scenario_controller_find_all_request_sort_order import ScenarioControllerFindAllRequestSortOrder
from .types.update_scenario_dto_hooks_item import UpdateScenarioDtoHooksItem
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSimulationScenariosClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def scenario_controller_find_all(
        self,
        *,
        id_any: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        name: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[ScenarioControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[ScenarioControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[Scenario]]:
        """
        Returns the scenarios for the authenticated organization.

        Parameters
        ----------
        id_any : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Return only scenarios matching the provided ids

        name : typing.Optional[str]
            Search by scenario name

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[ScenarioControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[ScenarioControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[Scenario]]

        """
        _response = self._client_wrapper.httpx_client.request(
            "eval/simulation/scenario",
            method="GET",
            params={
                "idAny": id_any,
                "name": name,
                "page": page,
                "sortOrder": sort_order,
                "sortBy": sort_by,
                "limit": limit,
                "createdAtGt": serialize_datetime(created_at_gt) if created_at_gt is not None else None,
                "createdAtLt": serialize_datetime(created_at_lt) if created_at_lt is not None else None,
                "createdAtGe": serialize_datetime(created_at_ge) if created_at_ge is not None else None,
                "createdAtLe": serialize_datetime(created_at_le) if created_at_le is not None else None,
                "updatedAtGt": serialize_datetime(updated_at_gt) if updated_at_gt is not None else None,
                "updatedAtLt": serialize_datetime(updated_at_lt) if updated_at_lt is not None else None,
                "updatedAtGe": serialize_datetime(updated_at_ge) if updated_at_ge is not None else None,
                "updatedAtLe": serialize_datetime(updated_at_le) if updated_at_le is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[Scenario],
                    construct_type(
                        type_=typing.List[Scenario],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def scenario_controller_create(
        self,
        *,
        name: str,
        instructions: str,
        evaluations: typing.Sequence[EvaluationPlanItem],
        hooks: typing.Optional[typing.Sequence[CreateScenarioDtoHooksItem]] = OMIT,
        target_overrides: typing.Optional[AssistantOverrides] = OMIT,
        tool_mocks: typing.Optional[typing.Sequence[ScenarioToolMock]] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Scenario]:
        """
        Creates a scenario, the AI tester's intent plus the success criteria that score a run.

        Parameters
        ----------
        name : str
            The display name of the scenario, for example `Book an appointment`.

        instructions : str
            What the AI tester should try to accomplish in the conversation. Write it as the AI tester's goal, for example `Book an appointment for next week and confirm the time.`

        evaluations : typing.Sequence[EvaluationPlanItem]
            The checks that decide whether a run passes. Each evaluation compares a structured output against an expected value. At least one evaluation is required to run.

        hooks : typing.Optional[typing.Sequence[CreateScenarioDtoHooksItem]]
            Hooks to run on simulation lifecycle events

        target_overrides : typing.Optional[AssistantOverrides]
            Overrides to inject into the simulated target assistant or squad

        tool_mocks : typing.Optional[typing.Sequence[ScenarioToolMock]]
            Mock results for the assistant or squad's tools during the simulation, so the run stays deterministic without calling real services.

        path : typing.Optional[str]
            Optional folder path for organizing scenarios.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Maps to GitOps resource folder structure.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Scenario]

        """
        _response = self._client_wrapper.httpx_client.request(
            "eval/simulation/scenario",
            method="POST",
            json={
                "name": name,
                "instructions": instructions,
                "evaluations": convert_and_respect_annotation_metadata(
                    object_=evaluations, annotation=typing.Sequence[EvaluationPlanItem], direction="write"
                ),
                "hooks": convert_and_respect_annotation_metadata(
                    object_=hooks, annotation=typing.Sequence[CreateScenarioDtoHooksItem], direction="write"
                ),
                "targetOverrides": convert_and_respect_annotation_metadata(
                    object_=target_overrides, annotation=AssistantOverrides, direction="write"
                ),
                "toolMocks": convert_and_respect_annotation_metadata(
                    object_=tool_mocks, annotation=typing.Sequence[ScenarioToolMock], direction="write"
                ),
                "path": path,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Scenario,
                    construct_type(
                        type_=Scenario,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def scenario_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Scenario]:
        """
        Returns the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Scenario]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/scenario/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Scenario,
                    construct_type(
                        type_=Scenario,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def scenario_controller_remove(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Scenario]:
        """
        Deletes the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Scenario]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/scenario/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Scenario,
                    construct_type(
                        type_=Scenario,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def scenario_controller_update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        evaluations: typing.Optional[typing.Sequence[EvaluationPlanItem]] = OMIT,
        hooks: typing.Optional[typing.Sequence[UpdateScenarioDtoHooksItem]] = OMIT,
        target_overrides: typing.Optional[AssistantOverrides] = OMIT,
        tool_mocks: typing.Optional[typing.Sequence[ScenarioToolMock]] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Scenario]:
        """
        Updates the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        name : typing.Optional[str]
            This is the name of the scenario.

        instructions : typing.Optional[str]
            This is the script/instructions for the tester to follow during the simulation.

        evaluations : typing.Optional[typing.Sequence[EvaluationPlanItem]]
            This is the structured output-based evaluation plan for the simulation.
            Each item defines a structured output to extract and evaluate against an expected value.

        hooks : typing.Optional[typing.Sequence[UpdateScenarioDtoHooksItem]]
            Hooks to run on simulation lifecycle events

        target_overrides : typing.Optional[AssistantOverrides]
            Overrides to inject into the simulated target assistant or squad

        tool_mocks : typing.Optional[typing.Sequence[ScenarioToolMock]]

        path : typing.Optional[str]
            Optional folder path for organizing scenarios.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Set to null to remove from folder.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Scenario]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"eval/simulation/scenario/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "name": name,
                "instructions": instructions,
                "evaluations": convert_and_respect_annotation_metadata(
                    object_=evaluations, annotation=typing.Sequence[EvaluationPlanItem], direction="write"
                ),
                "hooks": convert_and_respect_annotation_metadata(
                    object_=hooks, annotation=typing.Sequence[UpdateScenarioDtoHooksItem], direction="write"
                ),
                "targetOverrides": convert_and_respect_annotation_metadata(
                    object_=target_overrides, annotation=AssistantOverrides, direction="write"
                ),
                "toolMocks": convert_and_respect_annotation_metadata(
                    object_=tool_mocks, annotation=typing.Sequence[ScenarioToolMock], direction="write"
                ),
                "path": path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Scenario,
                    construct_type(
                        type_=Scenario,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSimulationScenariosClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def scenario_controller_find_all(
        self,
        *,
        id_any: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        name: typing.Optional[str] = None,
        page: typing.Optional[float] = None,
        sort_order: typing.Optional[ScenarioControllerFindAllRequestSortOrder] = None,
        sort_by: typing.Optional[ScenarioControllerFindAllRequestSortBy] = None,
        limit: typing.Optional[float] = None,
        created_at_gt: typing.Optional[dt.datetime] = None,
        created_at_lt: typing.Optional[dt.datetime] = None,
        created_at_ge: typing.Optional[dt.datetime] = None,
        created_at_le: typing.Optional[dt.datetime] = None,
        updated_at_gt: typing.Optional[dt.datetime] = None,
        updated_at_lt: typing.Optional[dt.datetime] = None,
        updated_at_ge: typing.Optional[dt.datetime] = None,
        updated_at_le: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[Scenario]]:
        """
        Returns the scenarios for the authenticated organization.

        Parameters
        ----------
        id_any : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Return only scenarios matching the provided ids

        name : typing.Optional[str]
            Search by scenario name

        page : typing.Optional[float]
            This is the page number to return. Defaults to 1.

        sort_order : typing.Optional[ScenarioControllerFindAllRequestSortOrder]
            This is the sort order for pagination. Defaults to 'DESC'.

        sort_by : typing.Optional[ScenarioControllerFindAllRequestSortBy]
            This is the column to sort by. Defaults to 'createdAt'.

        limit : typing.Optional[float]
            This is the maximum number of items to return. Defaults to 100.

        created_at_gt : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than the specified value.

        created_at_lt : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than the specified value.

        created_at_ge : typing.Optional[dt.datetime]
            This will return items where the createdAt is greater than or equal to the specified value.

        created_at_le : typing.Optional[dt.datetime]
            This will return items where the createdAt is less than or equal to the specified value.

        updated_at_gt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than the specified value.

        updated_at_lt : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than the specified value.

        updated_at_ge : typing.Optional[dt.datetime]
            This will return items where the updatedAt is greater than or equal to the specified value.

        updated_at_le : typing.Optional[dt.datetime]
            This will return items where the updatedAt is less than or equal to the specified value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[Scenario]]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "eval/simulation/scenario",
            method="GET",
            params={
                "idAny": id_any,
                "name": name,
                "page": page,
                "sortOrder": sort_order,
                "sortBy": sort_by,
                "limit": limit,
                "createdAtGt": serialize_datetime(created_at_gt) if created_at_gt is not None else None,
                "createdAtLt": serialize_datetime(created_at_lt) if created_at_lt is not None else None,
                "createdAtGe": serialize_datetime(created_at_ge) if created_at_ge is not None else None,
                "createdAtLe": serialize_datetime(created_at_le) if created_at_le is not None else None,
                "updatedAtGt": serialize_datetime(updated_at_gt) if updated_at_gt is not None else None,
                "updatedAtLt": serialize_datetime(updated_at_lt) if updated_at_lt is not None else None,
                "updatedAtGe": serialize_datetime(updated_at_ge) if updated_at_ge is not None else None,
                "updatedAtLe": serialize_datetime(updated_at_le) if updated_at_le is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[Scenario],
                    construct_type(
                        type_=typing.List[Scenario],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def scenario_controller_create(
        self,
        *,
        name: str,
        instructions: str,
        evaluations: typing.Sequence[EvaluationPlanItem],
        hooks: typing.Optional[typing.Sequence[CreateScenarioDtoHooksItem]] = OMIT,
        target_overrides: typing.Optional[AssistantOverrides] = OMIT,
        tool_mocks: typing.Optional[typing.Sequence[ScenarioToolMock]] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Scenario]:
        """
        Creates a scenario, the AI tester's intent plus the success criteria that score a run.

        Parameters
        ----------
        name : str
            The display name of the scenario, for example `Book an appointment`.

        instructions : str
            What the AI tester should try to accomplish in the conversation. Write it as the AI tester's goal, for example `Book an appointment for next week and confirm the time.`

        evaluations : typing.Sequence[EvaluationPlanItem]
            The checks that decide whether a run passes. Each evaluation compares a structured output against an expected value. At least one evaluation is required to run.

        hooks : typing.Optional[typing.Sequence[CreateScenarioDtoHooksItem]]
            Hooks to run on simulation lifecycle events

        target_overrides : typing.Optional[AssistantOverrides]
            Overrides to inject into the simulated target assistant or squad

        tool_mocks : typing.Optional[typing.Sequence[ScenarioToolMock]]
            Mock results for the assistant or squad's tools during the simulation, so the run stays deterministic without calling real services.

        path : typing.Optional[str]
            Optional folder path for organizing scenarios.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Maps to GitOps resource folder structure.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Scenario]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "eval/simulation/scenario",
            method="POST",
            json={
                "name": name,
                "instructions": instructions,
                "evaluations": convert_and_respect_annotation_metadata(
                    object_=evaluations, annotation=typing.Sequence[EvaluationPlanItem], direction="write"
                ),
                "hooks": convert_and_respect_annotation_metadata(
                    object_=hooks, annotation=typing.Sequence[CreateScenarioDtoHooksItem], direction="write"
                ),
                "targetOverrides": convert_and_respect_annotation_metadata(
                    object_=target_overrides, annotation=AssistantOverrides, direction="write"
                ),
                "toolMocks": convert_and_respect_annotation_metadata(
                    object_=tool_mocks, annotation=typing.Sequence[ScenarioToolMock], direction="write"
                ),
                "path": path,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Scenario,
                    construct_type(
                        type_=Scenario,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def scenario_controller_find_one(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Scenario]:
        """
        Returns the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Scenario]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/scenario/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Scenario,
                    construct_type(
                        type_=Scenario,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def scenario_controller_remove(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Scenario]:
        """
        Deletes the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Scenario]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/scenario/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Scenario,
                    construct_type(
                        type_=Scenario,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def scenario_controller_update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        evaluations: typing.Optional[typing.Sequence[EvaluationPlanItem]] = OMIT,
        hooks: typing.Optional[typing.Sequence[UpdateScenarioDtoHooksItem]] = OMIT,
        target_overrides: typing.Optional[AssistantOverrides] = OMIT,
        tool_mocks: typing.Optional[typing.Sequence[ScenarioToolMock]] = OMIT,
        path: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Scenario]:
        """
        Updates the specified scenario.

        Parameters
        ----------
        id : str
            The unique identifier of the scenario.

        name : typing.Optional[str]
            This is the name of the scenario.

        instructions : typing.Optional[str]
            This is the script/instructions for the tester to follow during the simulation.

        evaluations : typing.Optional[typing.Sequence[EvaluationPlanItem]]
            This is the structured output-based evaluation plan for the simulation.
            Each item defines a structured output to extract and evaluate against an expected value.

        hooks : typing.Optional[typing.Sequence[UpdateScenarioDtoHooksItem]]
            Hooks to run on simulation lifecycle events

        target_overrides : typing.Optional[AssistantOverrides]
            Overrides to inject into the simulated target assistant or squad

        tool_mocks : typing.Optional[typing.Sequence[ScenarioToolMock]]

        path : typing.Optional[str]
            Optional folder path for organizing scenarios.
            Supports up to 3 levels (e.g., "dept/feature/variant").
            Set to null to remove from folder.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Scenario]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"eval/simulation/scenario/{jsonable_encoder(id)}",
            method="PATCH",
            json={
                "name": name,
                "instructions": instructions,
                "evaluations": convert_and_respect_annotation_metadata(
                    object_=evaluations, annotation=typing.Sequence[EvaluationPlanItem], direction="write"
                ),
                "hooks": convert_and_respect_annotation_metadata(
                    object_=hooks, annotation=typing.Sequence[UpdateScenarioDtoHooksItem], direction="write"
                ),
                "targetOverrides": convert_and_respect_annotation_metadata(
                    object_=target_overrides, annotation=AssistantOverrides, direction="write"
                ),
                "toolMocks": convert_and_respect_annotation_metadata(
                    object_=tool_mocks, annotation=typing.Sequence[ScenarioToolMock], direction="write"
                ),
                "path": path,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Scenario,
                    construct_type(
                        type_=Scenario,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
