# This file was auto-generated by Fern from our API Definition.

import typing

ListFilesRequestPurpose = typing.Union[
    typing.Literal["assistant", "composer-attachment", "knowledge-base-v2"], typing.Any
]
