# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .campaign_controller_find_all_request_sort_by import CampaignControllerFindAllRequestSortBy
    from .campaign_controller_find_all_request_sort_order import CampaignControllerFindAllRequestSortOrder
    from .campaign_controller_find_all_request_status import CampaignControllerFindAllRequestStatus
    from .campaign_controller_find_all_v_2_request_sort_by import CampaignControllerFindAllV2RequestSortBy
    from .campaign_controller_find_all_v_2_request_sort_order import CampaignControllerFindAllV2RequestSortOrder
    from .campaign_controller_find_all_v_2_request_status import CampaignControllerFindAllV2RequestStatus
    from .campaign_controller_get_campaign_v_2_contacts_request_sort_by import (
        CampaignControllerGetCampaignV2ContactsRequestSortBy,
    )
    from .campaign_controller_get_campaign_v_2_contacts_request_status_item import (
        CampaignControllerGetCampaignV2ContactsRequestStatusItem,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CampaignControllerFindAllRequestSortBy": ".campaign_controller_find_all_request_sort_by",
    "CampaignControllerFindAllRequestSortOrder": ".campaign_controller_find_all_request_sort_order",
    "CampaignControllerFindAllRequestStatus": ".campaign_controller_find_all_request_status",
    "CampaignControllerFindAllV2RequestSortBy": ".campaign_controller_find_all_v_2_request_sort_by",
    "CampaignControllerFindAllV2RequestSortOrder": ".campaign_controller_find_all_v_2_request_sort_order",
    "CampaignControllerFindAllV2RequestStatus": ".campaign_controller_find_all_v_2_request_status",
    "CampaignControllerGetCampaignV2ContactsRequestSortBy": ".campaign_controller_get_campaign_v_2_contacts_request_sort_by",
    "CampaignControllerGetCampaignV2ContactsRequestStatusItem": ".campaign_controller_get_campaign_v_2_contacts_request_status_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CampaignControllerFindAllRequestSortBy",
    "CampaignControllerFindAllRequestSortOrder",
    "CampaignControllerFindAllRequestStatus",
    "CampaignControllerFindAllV2RequestSortBy",
    "CampaignControllerFindAllV2RequestSortOrder",
    "CampaignControllerFindAllV2RequestStatus",
    "CampaignControllerGetCampaignV2ContactsRequestSortBy",
    "CampaignControllerGetCampaignV2ContactsRequestStatusItem",
]
